- fzf
When the curses gem is not installed and the session is running inside
tmux the user will see a flash of an opened and closed tmux pane but
will not have a chance to read the error message.
> Sleep when curses is unavailable

- install
When using the widget in "/", it would descend into 'dev/'.
Using '*' for the starting path would do so also with the new '-fstype'
excludes.
The drawback / change now is that the './' prefix is being added, which
I don't mind.  This could be fixed by throwing in some `cut -b3-` into
the pipe.
> Improve `find` command for cd widgets: exclude proc/dev

- plugin/fzf.vim
Hi, Junegunn!
Prior to this change, you'd get a longer error message if you did:
:FZF
<esc>
:FZF
The main problem being that `:file [FZF]` can be used only once. This commit uses that to its advantage and just adds a simple `bufexists('[FZF]')` check (and a warning message, that you can remove if you want).
Probably easier than using an ugly `s:is_active` variable. :)
> Check if :FZF is already executing

- plugin/fzf.vim
#180 only fixes invocations of `:FZF`. This simply moves the check to `fzf#run()` so that it works with all invocations of fzf.
> Check if fzf#run() is already executing

- install
Problem: `yes n | ./install` should answer "n" to every prompt, but instead it answers "n" to the first question, and the next question is getting some non-printable input which `ask()` interprets as "y". This means that shell keybindings are always installed. 
Solution: omit `-n 1` for non-interactive shells.
> install: wait for LF in non-interactive shell

- shell/key-bindings.fish
Turns out fish key bindings support different modes, so that adding the functionality was a matter of binding the given shortcuts also to the insert mode.
> Support for vi insert mode in upcoming fish 2.2.0

- shell/key-bindings.zsh
at least my version of head wants -n1 to only display the first line
> fix typo in argument of head (zsh completion)

- src/curses/curses.go
Assigning to stdin, stdout and stderr is not portable. They're specified
to be macros, and for example musl will not allow such code to be
compiled.
Use dup2 instead.
> Portable implementation of swapOutput

- src/core.go
- src/options.go
- src/reader.go
Simplified reader and added a configurable delimiter. Added "--null" option to interface.
Not sure I added the help line in the right place. Feel free to fix it yourself.
> add support to nil-byte separated input strings, closes #121

- plugin/fzf.vim
To avoid conflict with other neoterm plugins that manage terminals,
prefer named terminals.
> Avoid conflict with other neoterm plugins.

- shell/key-bindings.zsh
In addition to being simpler and not relying on zsh options, it allows subsequent up/down history or accept-line-and-down-history widgets to work.
I also replaced your pipeline for extracting the number with what I think is simpler: assign the output to an array and then take the first element.
Furthermore, The cd widget didn't work in my configuration because of two aliases I have defined:
alias find='noglob find'
alias command='command '
The later enables alias expansion after command. It'd be better to use zsh's autoloadable functions: put the functions each in their own file, .fzf.zsh would then need to add that directory to fpath:
fpath+=( $fzf_base/shell/fpath )
and autoload them with the -U option to disable alias expansion:
autoload -Uz fzf-history-widget fzf-file-widget …
> use vi-fetch-history on zsh to get history line

- shell/completion.bash
Hi!
There is a problem with a `g++` Bash autocompletion:
`g++`<kbd>space</kbd><kbd>tab</kbd> causes `g++ bash: warning: programmable_completion: g++: possible retry loop`
How to reproduce:
Ubuntu 14.04
Bash-4.3
bash-completion-2.1
`source ~/.fzf.bash` after `source /usr/share/bash-completion/bash_completion` in `~/.bashrc`
See http://unix.stackexchange.com/q/213432/120177
> Fix g++: possible retry loop

- plugin/fzf.vim
The SwapExists dialog prevents multiple files from being opening if the
dialog occurs before all files are opened. Opening the files is more
important than showing the dialog, so choose "readonly" automatically
and continue opening files.
This problem exists in neovim and Vim 7.3. Not sure about others. To test, choose multiple files in the `:FZF` prompt; if a swap-exists dialog appears before all files are opened, those remaining files will not be opened.
> [vim] handle SwapExists

- plugin/fzf.vim
Attempting to edit a directory in a `try` block in Vim silently fails to trigger the autocommands used by file browsers (netrw, vimfiler, probably others). Adding a BufEnter autocommand after the edit command if the item was a directory allows netrw to work instead of opening a blank buffer.
> Trigger netrw autocommand when opening directory

- shell/key-bindings.zsh
In the case that fzf-tmux returns a user-selected result but with a
non-zero exit status (for reasons I haven't figured out quite yet) this
allows CTRL-R to continue working as expected.
Addresses #203 (Tranquility's comment)
> Not relying on exit status for CTRL-R

- shell/completion.bash
Allow `**<tab>` completion for Neovim command.
> [bash-completion] Add nvim to f_cmds

- shell/completion.zsh
This also fixes the completion causing a bell / flickering in case
"shwordsplit" was not set, because then the function would return false.
> zsh: fzf-completion: use noshwordsplit local option

- bin/fzf-tmux
- plugin/fzf.vim
Here's a slightly hacky approach to supporting zoomed windows:
1. Create temporary window and move the zoomed pane to the tmp window
2. Do the normal fzf-tmux thing
3. Move the zoomed pane back to the original window, kill the tmp window, and re-zoom
It's a bit fragile, for a couple reasons:
- If the user starts moving around windows while fzf-tmux is open they'll notice that something is odd
- If the user tries to select one of the hidden panes while fzf-tmux is open they'll notice that they are not there
I generally don't do much tmuxing around while fzf is open, though, so this seems good enough for my workflow.  Btw, the approach of creating a tmp window is based on this stack overflow answer:
http://superuser.com/a/357799
> Support fzf-tmux when zoomed

- bin/fzf-tmux
I think this method of checking whether we're in a tmux session is more robust.  Using `$TMUX_PANE` doesn't work when I do something like `bind-key t run -b foo`, where `foo` is a script that uses `fzf-tmux`.
> Correct fzf-tmux tmux checking bug

- shell/key-bindings.bash
- Don't assume ~/.fzf.bash exists.
- Source the current script for `__fzf_select__`.
- Forward `$PATH`.
- Dynamically select which `__fzf_select__` to use.
> Fix CTRL-T in tmux.

- shell/key-bindings.bash
FZF_DEFAULT_OPTS are lost when CTRL+T invokes `__fzf_select__` in a new tmux window.
> Pass FZF_DEFAULT_OPTS to non-interactive bash instance

- shell/completion.bash
- shell/completion.zsh
Should fix `ls /**` for both bash (tested) and zsh (not tested)
While testing I also noticed `ls dir**` is broken if both `dir` and `dirAbc` exist in your cwd (dirAbc[/*] not listed).
I'll have a look at it tomorrow, if not I'll create an issue.
> Fix autocompletion for absolute paths

- man/man1/fzf.1
If you do `man fzf > /dev/null`, you'll get the following output
`R' is a string (producing the registered sign), not a macro.`
`R' is a string (producing the registered sign), not a macro.`
`R' is a string (producing the registered sign), not a macro.`
`R' is a string (producing the registered sign), not a macro.`
`R' is a string (producing the registered sign), not a macro.`
`R' is a string (producing the registered sign), not a macro.`
Removing these `.R` macros has no effect on the rendering of the page but
gets rid of the error.
> Removed the useless `.R` macros

- src/matcher.go
Fixes the following error:
```
src/matcher.go:203: syntax error: unexpected range, expecting {
src/matcher.go:207: non-declaration statement outside function body
src/matcher.go:208: syntax error: unexpected }
```
While not all distributions ship Go 1.4 (Debian 8, Ubuntu 15.04) yet, this negligible fix makes it possible to build against 1.3.
> Go 1.3 compatibility

- plugin/fzf.vim
Fixes "E706: Variable type mismatch for: ret" when an exception is caught.
> s:callback: Always return list.

- shell/key-bindings.bash
Summary:
Fix from: https://adamheins.com/blog/fzf-vi-mode-and-fixing-delays
(Thanks, @adamheins!)
The basic problem is that
fzf presses <Esc> to enter vi-movement-mode
(as opposed to insert mode)
and then presses a bunch of keys to set up the buffer.
But the <Esc> keypress is also the prefix for a bunch of other commands,
so Bash will dutifully wait an excruciating half-second
before actually executing this command.
Instead, we bind <C-a>, which is unused by default,
to be another way to enter vi-movement-mode;
this binding is unambiguous, so fzf can use it without delay.
This change was made by just `:s/\\e/\\C-a/gc` in the relevant section,
after adding the actual binding and comment at the top.
> Fix Bash+vimode pre-launch delay

- src/Makefile
The `Build on $(UNAME_M) is not supported, yet` message was referencing an undefined UNAME_M. Fixed that.
Still I'm thinking is there sense to keep this warning? Apparently it builds just fine on my i686 system. So why should the Makefile be disabled forcefully?
> Fix missing reference to UNAME_M

- bin/fzf-tmux
Hello!
I'm having the following problem while using fzf with custom tmux keybindings required to work with vim-tmux-navigator:
I use C-h/j/k/l shortcut to navigate between vim and tmux splits, but the same shortcuts are used to iterate over lists in fzf split. vim-tmux-navigator basically solves the problem of shortcuts clash between tmux and vim using *if-shell* statement inside tmux config that detects the current command of the pane and sends appropriate commands to current pane.
The same solution would apply to fzf if only there were a way to detect that current split is running fzf. Currently it's impossible because there is no identity of fzf in the tmux pane - the active command is bash.
This commit changes the tmux pane title to "fzf" which allows to differentiate it in tmux …
> Change tmux pane title for fzf splits

- shell/completion.zsh
I spent the past few hours doing a bit of yak shaving on speeding up my `zsh` startup time and discovered that one of the biggest bottlenecks was this chunk of code in `shell/completion.zsh`! 😮 
The slowdown is a result of launching the `grep` and `awk` programs to set the `fzf_default_completion` environment variable. I rewrote the code to use only zsh built-ins and got a reasonable speedup! Here are the results:
```
All times in microseconds (us), 100 samples each
=====
Control       -- Mean: 9035.12, Stddev: 326.39
Experiment    -- Mean: 5979.47, Stddev: 372.748
```
[Here is a gist of the script I used](https://gist.github.com/anonymous/3ecef48effacc72f205ed40a58b3112d) to profile the control (i.e. `junegunn master`) vs the experiment (i.e. this PR).
FYI: here are the 25 slowest lines …
> optimize fzf_default_completion binding

- shell/completion.zsh
- shell/key-bindings.zsh
zle automatically calls zle-line-init when it starts to read a new line. Many
Zsh setups use this hook to set the terminal into application mode, since this
will then allow defining keybinds based on the $terminfo variable (the escape
codes in said variable are only valid in application mode).
However, fzf resets the terminal into raw mode, rendering $terminfo values
invalid once the widget has finished. Accordingly, keyboard bindings defined
via $terminfo won’t work anymore.
This fixes the issue by calling zle-line-init when widgets finish. Care is taken
to not call this widget when it is undefined.
Fixes #279
> [zsh] Re-initialize zle when widgets finish

- shell/key-bindings.bash
The command `tmux send-keys` is really not intended for text I don't believe. Instead, we should use a buffer. The buffer can be deleted right after it's used.
This solves the problem of if you select a filename with ctrl+t that has unicode characters in them. I noticed this when selecting song files that were in different languages. The output was corrupted, and could not be used in commands.
This should fix the problem, and I do not believe this problem is anywhere else in the code.
Actually I'm not sure why ctrl+t needs a special function like this in bash only, but I haven't looked at the other shells' implementations to see how it works for them.
(Also I am working on a keybindings port to mksh, if you are interested in merging that as well.)
> use tmux buffers for sending output to preserve character encoding

- plugin/fzf.vim
`termopen` no longer accepts a `name` option, instead we should suffix the
command with `;#NAME`.
> Remove `name` option from `termopen`.

- shell/completion.zsh
The command substitution and following word splitting to determine the default
zle widget for ^I formerly only works if the IFS parameter contains a space. Now
it specifically splits at spaces, regardless of IFS.
> Split default zsh binding at the correct place

- bin/fzf-tmux
Fixes #643
Doesn't break #648 
Note that this will break if the socket filename contains any commas, but in my testing, tmux completely stopped functioning when I put a comma in the socket filename.
> Make fzf target correct session in group

- shell/completion.zsh
I'm using macOS, but I've installed gnu coreutils from homebrew. By default, in order to avoid conflicts with system utils, they are prefixed with a `g`, eg. `ls` is installed as `gls` and so on.
There is a zsh module (from prezto) that wraps these utils in functions so that I can use them without the prefix in interactive shells. For example:
``` bash
$ which -a cat
cat () {
'/usr/local/bin/gcat' "$@"
}
/bin/cat
```
And so on.
This PR fixes some issues I encountered with this setup. In particular `[` and `cat`. I've also tested these changes on 'vanilla' zsh (using system utils, no gnu-coreutils) and nothing breaks.
Autocomplete with `**<tab>` would print an error like:
```
vi **/usr/local/bin/g[: missing argument after ‘-d’
```
From the bsd man page for `test`. I assume this is the same …
> Zsh script improvements

- plugin/fzf.vim
This is the case for very recent Neovim builds, but works with older versions
as well.
---
Explanation: https://github.com/neovim/neovim/wiki/Following-HEAD#20161212
Closes #765.
> Neovim: event handlers always expect three arguments

- README.md
- shell/key-bindings.fish
Replace the "temp file" workaround with the "read" function: it's
simpler and faster.
Use proper escaping, remove the custom function.
The "file" widget uses last token as root for the "find" command.
This replaces the equivalent of '**' completion in bash/zsh.
The "$cwd" non-expanded variable can be used in FZF_CTRL_T_COMMAND to
set the root.
This closes #443, #484, #486 and #747.
> Overhaul fish functions

- plugin/fzf.vim
With a `bufhidden=wipe` buffer (e.g. vim-startify) the buffer would not
exist anymore, resulting in an error.
> s:execute_term: switch_back: check that self.pbuf exists

- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
This removes the need for the 'sed' call. Faster, cleaner.
> shell: Use '-mindepth 1' to omit root folder in 'find' output

- plugin/fzf.vim
When running Vim on Windows,
- use cmd.exe as launcher and shell
- enable shellslash within s:cmd()
- don't escape ' ' and '\\' for paths
> [vim] Use cmd.exe in Windows

- plugin/fzf.vim
PR for the commit https://github.com/janlazo/fzf/commit/4572bdcf7d710d8dcc4460319c0ac0f0a1878216, referenced in #786, for the gui launcher on Windows
Tested on GVim 8 and Windows 8.1
> [vim] use cmd.exe directly on GVim (launcher='%s')

- plugin/fzf.vim
Later versions of Vim/Nvim handle `:edit <dir>` inside try-catch.
https://github.com/vim/vim/commit/e13b9afe1283f5ae43232b5992372a0eb570666c
https://github.com/vim/vim/pull/1375
> s:common_sink(): Avoid duplicate BufEnter.

- plugin/fzf.vim
This can be useful to add the current command name to the statusline,
like this:
```viml
au User FzfStatusLine call <SID>fzf_statusline()
function! s:fzf_statusline()
let fzf_cmd_name = get(g:, 'fzf_cmd_name', 'FZF')
let &l:statusline = '> '.fzf_cmd_name
endfunction
```
> Add current command name on a global variable

- shell/completion.bash
- shell/completion.zsh
Without this patch, IPv6 addresses are not parsed completely in the ssh known_hosts file.
Signed-off-by: Sam Van Den Berge <sam@drgt.net>
> Add support for IPv6 addresses in ssh ** command

- install
This change makes the install scripts work on non GNU tar systems as well (which at least includes FreeBSD).
> make install script work with non GNU tar

- plugin/fzf.vim
This displays the buffer(s) in this case, which is useful when FZF got
stuck, and you have to manually remove the buffer.
> fzf#run: improve "is already running" message

- bin/fzf-tmux
Hi, thanks for your great tool! 
FZF greatly changed my terminal life.
I'm sorry If this PR broke something or is duplicated issue, but I have the following problem.
When I zoom one pane, and use `fzf-tmux`, then a pane will be killed.
I took a short movie to describe it:
I read this pull request, but I couldn't understand why the line 
`bash -c 'while :; do for c in \\| .... ` is added...
https://github.com/junegunn/fzf/pull/433
It seems that swapping `tmp_window` and `original_window` is not working correctly.
Thanks!
```
fzf --version
0.16.6
bash --version
GNU bash, version 4.4.12
```
- Category
- OS
- Shell
> fix fzf-tmux kill another pane when zoomed

- bin/fzf-tmux
> Fixed #796

- plugin/fzf.vim
- Category
- OS
- Shell
PR for the shellescaping issue I described in #882.
I added wrapper functions to handle filepath functions in vim.
- `set noshellslash` for backslash in filepaths
- `set shellslash` for `shellescape()` to single quote first, and then double quote its output   (ex. path --> "'path'")
- Vim runs cmd.exe twice, one is a wrapper proxy, and the other is the actual command
- cmd.exe strips the double quotes of each argument
- `C:\Program Files (x86)\` (no quotes) breaks on `s:execute()` so it must be escaped with single/double quotes in cmd.exe and powershell
I wasn't sure where to put the new functions so I placed them just after if guard at the top of the file because I used `fzf#expand` for `s:base_dir`.
> [vim] Use backslash for Windows filepaths

- src/tui/light.go
- src/util/util_unix.go
- src/util/util_windows.go
> use read syscall directly to get character

- plugin/fzf.vim
- test/fzf.vader
Continuation of #896.
Previous PR cannot escape double quotes properly in `s:evaluate_opts` because of escaping assumptions made by cmd.exe. Instead on relying `shellescape` which relies on `shellslash`, use `s:shellesc` to escape with `\` in Unix and `\^` in Windows. For now, only `"` is escaped this way. The last backslash is escaped the same way as in `s:fzf_shellescape`.
The outer double quotes are escaped via `^` so cmd.exe knows where the escaping starts and ends. Without it, shell redirection with `>` fails even if the double quote character is escaped.
```dosbatch
> fzf --prompt "C:/Program \" Files (x86)/" "--multi" > tmp.txt
unknown option: >
```
> [vim] Replace s:fzf_shellescape and s:shellesc with fzf#shellescape

- plugin/fzf.vim
Some commands in fzf.vim use utf-8 characters but cmd.exe doesn't use utf-8 by default.
Permanently changing the encoding in cmd.exe or powershell affects other terminal programs so a temporary variable is required to store the current encoding and reverting to it after fzf runs successfully.
Issue is if the command fails, then terminal users are left in a bad state with a permanently changed encoding.
This change is limited to Windows and GUIs that use external terminals for fzf should be unaffected if the fzf fails.
This PR should resolve fzf.vim commands that use utf-8 characters such as `Commands`
Reference:
https://ss64.com/nt/chcp.html
> [vim] use utf-8 for cmd.exe

- plugin/fzf.vim
Since cygwin sh/bash runs cmd.exe in the back (sh/bash by itself is run in a cmd.exe terminal) and use  `TERM=cygwin`, we can run cygwin vim and the fzf (Windows) binary in cmd.exe/powershell. Benefit of including cygwin support to the vim plugin is running the tests as is in Windows. I'm currently using this for the Vader tests.
By unsetting TERM, fzf runs as if vim (Windows) is used. cygpath (via `s:cygpath`) is used for path conversion between Windows and cygwin filepaths. I updated `s:escape` to escape `()` for Windows filepaths.
Currently, this PR does not support mintty (`TERM=xterm`) because fzf is run inline (no shell script or batchfile) and I can't get the start command to work with shell redirection yet. Neovim TUI in cygwin sh/bash is not supported in the vim plugin even …
> Support cygwin vim via cygpath and Windows binary

- CHANGELOG.md
Also changed the example binding for `unix-word-rubout` to *ctrl-w* instead of *ctrl-u*
> Updates CHANGELOG with unix-line-discard+top

- test/fzf.vader
I commented out a `shellescape` test case for cmd.exe in PR #916.
This PR uncomments it and fixes the runaway single quote.
> [vader] uncomment test case to escape % in cmd.exe

- shell/key-bindings.fish
Fixes #945. If a selection is successfully chosen, the current commandline token should be "consumed".
> [fish] Fix <C-t> completion for current dir search

- shell/key-bindings.fish
Tested to work against fish 2.4 on Debian Stretch. I will be able to test against OS X tomorrow.
Fix found by @amosbird at https://github.com/junegunn/fzf/issues/953#issuecomment-310309055
closes #436
> [fish] Support multiline commands

- plugin/fzf.vim
cmd.exe leaves the pipe hanging for the source command after fzf finishes so powershell and ag keep running and cmd.exe does not close. Putting `FZF_DEFAULT_COMMAND` in a batchfile hides the issue from cmd.exe so Vim is stuck waiting and Neovim does not run the exit callback. Letting fzf run `FZF_DEFAULT_COMMAND` passes the responsibility of stopping the source program to fzf executable so Vim/Neovim don't have to wait for the source command to finish executing.
This issue does not happen when running the fzf executable directly in the shell if `FZF_DEFAULT_COMMAND` is using powershell. ag still gets stuck.
I did not consider ack because it requires perl and is too slow as a default command.
> [vim] Don't pipe FZF_DEFAULT_COMMAND in Windows

- plugin/fzf.vim
#896 did not consider relative filepaths in the exit handler because `dir /s/b` outputs absolute paths. I changed dict and temp to be part of the fzf job config to minimize issues with the exit handler when running `:FZF` consecutively in Neovim.
> [neovim] Fix lcd when fzf job exits on Windows

- shell/key-bindings.fish
... but multiline won't be supported in versions <2.4
Issue #966
I have yet to test this on version 2.3, but will.
> [fish] Fix ctrl-r regression in versions <2.4

- install
Add install support for http://www.mingw.org/
Running uname -sm yields:
MINGW32_NT-6.2 i686
The prebuilt windows 386 binary works well in this environment.
> Add MinGW on Windows to install script

- install
Need it for installing fzf in Windows 64-bit if running sh.exe (msysgit) from cmd.exe or powershell.exe
```dosbatch
:: within cmd.exe terminal
sh .\install --bin
```
> Add MinGW 64 to install fzf in Windows 64-bit

- plugin/fzf.vim
- test/fzf.vader
Forgot to handle the single backslash case which breaks the surrounding `^"` to wrap the entire string.
A use case is searching for backslash in `Lines`, `BLines`.
Requires `s:q` using `fzf#shellescape` in fzf.vim (commit: https://github.com/janlazo/fzf.vim/commit/32756d271a580c9d189dcc8dd053f8dd0731d9c8)
> [vim] escape backslashes in fzf#shellescape

- plugin/fzf.vim
Previously a command like `echo a && echo b` would get transformed into
`echo a && echo b | fzf`, which only pipes the output of the second
command. Adding parentheses around the source command avoids this issue,
and works on both Unix and Windows.
Caveat: I haven't tested this change on Windows, just played with some example
commands in the cmd.exe terminal.
> add parens around piped source commands

- bin/fzf-tmux
Based on [this issue](https://github.com/junegunn/fzf/issues/1032).
Adds a fix to the fzf-tmux script for newer distros that use a particular version of `tput`, specifically Fedora 26 and Debian 10, which causes fzf-tmux to fail when run inside tmux's `run-shell` command.
The fix falls back to using tmux's `pane_width` and `pane_height` command to set the `$lines` and `$columns` variable, but only if `tput lines` or `tput cols` fails.
Dockerfile for verifying that this works:
```Dockerfile
FROM docker.io/fedora:26
RUN dnf install -y tmux git curl
RUN git clone https://github.com/mike-hearn/fzf ~/.fzf && \
cd ~/.fzf && \
git checkout fedora26-tput-fix && \
~/.fzf/install --all
```
> Add fzf-tmux pane_height/pane_width fallback

- plugin/fzf.vim
Initial work to use the neovim terminal by default in Windows.
The double keypress remains for Windows 8+ because https://github.com/gdamore/tcell/pull/159 is unresolved.
I prefer to keep this open/unmerged until the 0.2.1 release while I test this with my pull requests in fzf.vim.
@mikesmiffy128 I cherry-pick the commit as you suggested in https://github.com/junegunn/fzf/pull/962#issuecomment-322936545
> Use the terminal by default for nvim-0.2.1 or GVim (nightly)

- plugin/fzf.vim
Cygwin converts unix-style paths to windows-style paths so `s:shortpath` shouldn't use `pathshorten` if `has('win32unix')`. `Files` has the same issue.
To reproduce
```sh
cd /usr/bin
fzf --prompt '/u/bin'
```
> [vim] do not pathshorten prompt in cygwin

- install
If `.bashrc`/`.zshrc` doesn't exist, the install script will create an empty `.bashrc`/`.zshrc` even if `n` is answered to `Do you want to update your shell configuration files?`. This is a bit of unexpected behavior, e.g. a script which installs `fzf` and then symlinks `.zshrc` from somewhere else will fail.
Ex:
```
[ -f ~/.zshrc] && mv ~/.zshrc ~/.zshrc.bak
printf 'y\ny\nn\n' | ~/fzf/install
ln -s ~/dotfiles/.zshrc ~/.zshrc
```
> Don't touch dotfiles if not requested

- README.md
The current ones are outdated and no longer work.
> Updated Linuxbrew instructions

- shell/completion.bash
- shell/completion.zsh
With an entry in `~/.ssh/config` like:
```
Host my-server example-server my-example-server
User josh
Hostname example.com
```
...using FZF's completion on `ssh **`, I only get the primary name listed. With this patch, the other aliases should also be selectable:
```
$ ssh **
>
3/3
> my-server
example-server
my-example-server
```
Thanks,
Josh
> _fzf_complete_ssh: include host aliases

- bin/fzf-tmux
This is a little improvement useful for my use case, but feel free declining it.
I'm a [tmux](https://github.com/tmux/tmux/wiki) user and I uses a key binding which depending on the current execution process does several things.
```tmux
is_fzf='echo "#{pane_current_command}" | grep -iqE "(^|\/)fzf$"'
bind -n C-h run-shell "($is_vim && tmux send-keys C-h) || \
($is_fzf && tmux send-keys C-h) || \
($is_zsh_prompt && tmux send-keys C-h) || \
tmux select-pane -L"
```
Currently if fzf is the current execution process, the process name is ``bash``. With these changes the process name is ``fzf`` and I'm able to capture it in tmux.
> Executes fzf from fzf-tmux with a process name

- shell/key-bindings.zsh
This would prevent tabs from being escaped as `$'\t'` (definitely not what I would want to see as initial value in the search).
> Don't do shell quoting for weird chars

- shell/completion.bash
- shell/completion.zsh
My known_hosts file has a lot of records like this:
[20.20.7.168]:9722 ssh-rsa ...
This is a standard format for servers running on custom port according to http://man.openbsd.org/sshd.8#SSH_KNOWN_HOSTS_FILE_FORMAT
A hostname or address may optionally be enclosed within ‘[’ and ‘]’ brackets then followed by ‘:’ and a non-standard port number.
> Fix known_hosts completion for custom port number

- shell/key-bindings.zsh
Using fc -r instead of fzf --tac in the zsh history widget allows for faster load times and causes less screen flicker.
> Use fc -r instead of fzf --tac to speed up loadtime

- shell/completion.bash
- shell/completion.zsh
When `ps` is aliased for something uncommon, like `alias ps=grc ps` which colorizes ps output, the output of `ps` can be unexpected and/or undesired.
This change makes ps to be always executed as command, even if it's aliased.
> Ensure ps called as command

- .gitignore
On Cygwin and MinGW, the fzf binary will have a .exe extension, so
ignore that binary if it exists as well as the bare binary.
> Add bin/fzf.exe to .gitignore

- README.md
The `Respecting .gitignore` link pointed to a section of the readme which no longer exists.
> Fix broken link in readme TOC

- README.md
Hi! fzf is now available in Fedora 26+; here are some instructions for installing that way.
> Add Fedora installation information.

- plugin/fzf.vim
> [vim] Don't use :terminal on msys2 or Cygwin

- install
The current install script hints that `y` will be the default answer to the various prompts, but if the user presses `Enter` without entering an answer, nothing happens.
This PR sets the default answer to `y` as hinted in the prompt `[y]/n` so that the user can keep pressing `Enter` to accept the default answer.
> Make default answer "y" in install script

- src/constants.go
- src/util/util_windows.go
Retry #971 but don't use `dir`. Instead, use `for /r`. It outputs the same files as `dir /a:-d/s/b`.
Problem is ending the for loop when fzf exits. I don't know what's causing cmd.exe to not terminate.
I added `v:on` flag for now so fzf doesn't run a subshell.
> Default command outputs relative filepath on Windows (take #2)

- README.md
Just documenting inverse prefix exact match search syntax.  Maybe there was a reason for not including this?  Or maybe it was just forgotten?  😊
> Document inverse prefix exact match search syntax

- bin/fzf-tmux
The `fzf-tmux` script disables the tmux `synchronize-panes` and `remain-on-exit` window options without restoring the original values. This PR fixes that by saving the original values of these options and restoring them on exit.
Note: This fix suffers from a race condition which can result in incorrect and unexpected behaviour if `fzf-tmux` is run concurrently in more than one pane of the same tmux window. I don't think it's possible to avoid that without maintaining some global state for each tmux window, which I think is undesirable and unnecessarily complicated given that this is quite unlikely to occur anyway.
> Restore tmux window options

- install
- uninstall
This makes it possible to keep your home directory free from fzf dotfiles. One thing to note is that this does not handle the case where a ~/.fzf.bash file already exists. I can include that if desired.
> Support for XDG Base Directory Specification

- shell/completion.bash
- shell/completion.zsh
`cat foo**<TAB>` did not display the file `foobar` if there was a directory
named `foo`.
Fixes #1301
> [bash, zsh] Fix missing fuzzy completions

- README.md
- man/man1/fzf.1
- src/options.go
- src/terminal.go
- test/test_go.rb
I'm quite used to have a prompt at the bottom of the screen (not to mention vim & emacs) while I prefer a list of items shown from top down.  I just don't want to be distracted by what I type but just like to concentrate on what to pick.
So, I've extended the `--reverse` option so it optionally takes `all`, `items` or `none` so you can choose which area to reverse.
> Provide an option to reverse items only

- shell/key-bindings.fish
This is the most simple fix I could think of for #1099 
If this is not robust enough for you or pre-mature (we can wait for fish 2.7 to be out), let me know.
Starting with fish 2.7 uppercase var are lowercases, see
https://github.com/fish-shell/fish-shell/issues/4414
or in case of $FISH_VERSION renamed, see also
https://github.com/fish-shell/fish-shell/commit/fb8ae04f80c3a129f789e7b718464d014508315f
> fish: Use $version instead of $FISH_VERSION

- shell/completion.bash
- shell/completion.zsh
Modern versions of SSH support a config option called HostKeyAlgorithms
that identifies the algorithms that will be offered or accepted (in the
case of SSHD). Since _fzf_complete_ssh does a case insensitive grep for
host, this line--if present--is also picked up.
The line being changed is:
https://github.com/junegunn/fzf/blob/master/shell/completion.bash#L244
The addition is: command grep -v 'HostKeyAlgorithms |'
> Do not match Host config options or ?-wildcards in SSH config file

- Makefile
- glide.lock
- glide.yaml
These patches add ppc64le to the build system and update the crypto lib to pull in a fix [1] for syscalls that's needed to get fzf working. These changes and building with Go 1.10 allows fzf to work on ppc64le (tested on Ubuntu 16.04). Building with Go 1.6-1.9 does not produce a working fzf, presumably due to bugs in Go.
[1] https://go.googlesource.com/crypto/+/558b6879de74bc843225cde5686419267ff707ca
Note: I'm not a Go user myself so I have no idea if the generated `glide.lock` file is correct, it's what was emitted when I did `glide update`.
> Support for ppc64le

- src/tui/light.go
If an ESC char is found whiile processing characters,
continue to check for characters. This prevent fzf from
prematurely exiting.
> Resolves #1349

- src/tui/light.go
Sometimes when `fzf` takes a while to startup, I start typing but my input gets dropped once the UI actually renders, and it's slightly annoying. It's rare (because `fzf` is usually quick), but noticeable particularly on first run after booting.
To reproduce, you can simulate a slow load with:
```
git ls-files | (sleep 1; fzf)
```
Currently anything you type in the first second will be dropped, with this change it gets consumed as search input once fzf loads.
I don't know if it's a bit weird to modify `r.buffer` during `findOffsets()`. It could alternatively return `(skipped, row, col)` and leave it up to the caller to add `skipped` to `r.buffer`, but that might get awkward.
I also don't know if this is the only place which needs this fix - is there a dark TUI as well as a light one?
> Don't drop buffered input data in findOffset()

- shell/completion.zsh
- shell/key-bindings.zsh
Builds upon PR https://github.com/junegunn/fzf/pull/1256, fixes the zsh multiline PS1 issue explained in https://github.com/junegunn/fzf/issues/867.
Tried this with both single and multi-line PS1 prompts and it works for both. This was inspired by a fix to a similar problem with pure (https://github.com/sindresorhus/pure) described here - https://github.com/sindresorhus/pure/issues/143, with the relevant fix here - https://github.com/sindresorhus/pure/pull/273/files#diff-ca464c5c9e47e8a26c7e6ac0ed786406R61.
I don't think this breaks anything, but it would be good to have someone else try this to make sure.
> fix multiline prompt issue with 'zle reset-prompt'

- shell/completion.zsh
Because I use 
`Include ~/.ssh/config.d/*`
on my ~/.ssh/config
Anyone knows how to put this into a FZF_SSH_CONFIG env var ?
> Also lookup on ~/.ssh/config.d/* files when doing ssh host complete

- README.md
... Since bat is pretty awesome :)
Similar to this PR from fzf.vim:
https://github.com/junegunn/fzf.vim/pull/712
Looks like this:
> [README.md] Add `bat` to preview syntax highlighting examples

- shell/completion.bash
Related to [previous issue](https://github.com/junegunn/fzf/issues/1170).
[Previous solution](https://github.com/junegunn/fzf/commit/d6588fc835aff6d952d86b1bdc5ed7378a846ab9#diff-c16a25d47a578fa3d03aa4328a4f59b0)
wouldn't work for commands with non-standard names, where `$cmd` and `$orig_cmd` differ,
e.g. `s.foo` -> `s_foo`
> [bash-completion] Fix custom completion for non-standard command names

- install
Just removing an unused variable that I detected when analyzing the install script.
> Remove allow_legacy variable in install script

- go.mod
- go.sum
A newer version of the sys module is
needed for pull request #1341
> Update sys module to newer version

- plugin/fzf.vim
Name-based colour specifications for guibg and guifg end up trying to call xterm with spurious backslashes. While this works for hex colours, it causes issues with the name-based colours. This removes the backslash in the format string and, instead, escapes the pound character as needed (i.e. if it is present).
> Fix name-based colours for gvim/8.0 without the in-built terminal

- shell/key-bindings.fish
Perl was used to remove the trailing newline character, but fzf already
has --print0 to use null character as terminators, and fish read -z is
expecting null character as terminators. There is no reason to depend on
perl if --print0 is passed to fzf invocation.
> Remove perl from fish key bindings.

- src/terminal.go
We're already trapping SIGTERM as well, not much else we can do.
> os.Kill signal cannot be trapped

- Makefile
I was attempting to build fzf inside termux on an android phone and it failed because the phone reports its architecture as "aarch64", not as "armv8l":
```
$ uname -a
Linux localhost 4.4.189-perf+ #1 SMP PREEMPT Wed Oct 2 11:49:20 UTC 2019 aarch64 Android
$ go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/data/data/com.termux/files/home/.cache/go-build"
GOENV="/data/data/com.termux/files/home/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="android"
GONOPROXY=""
GONOSUMDB=""
GOOS="android"
GOPATH="/data/data/com.termux/files/home/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/data/data/com.termux/files/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/data/data/com.termux/files/usr/lib/go/pkg/tool/android_arm64"
GCCGO="gccgo"
AR="ar" …
```
> Support building on machines with `uname -m` == "aarch64"

- plugin/fzf.vim
In recent Nvim versions, an "Error running ..." message is shown even for normal
use cases, such as:
:Files
<c-\><c-n>
:close
Closing the window will :bwipeout! the terminal buffer, because fzf sets
bufhiden=wipe.
When deleting the terminal buffer while fzf is still running, Nvim sends SIGHUP.
This happens for quite some time already, but the bug only manifests since this
commit:
https://github.com/neovim/neovim/commit/939d9053b
It's The Right Thing to do when the application exited due to a signal.
Before that commit, no "Error running ..." message was shown, because 1 (instead
of 128 + 1 == SIGHUP) was returned which the exit handler in fzf.vim treats as
"NO MATCH".
> Nvim: handle SIGHUP in exit handler

- install
uname (busybox) outputs `Windows_NT` on Windows 10 so `install` script could not download the binary. This PR should fix it.
> [install] Support busybox uname on Windows

- shell/key-bindings.zsh
The zsh version of the cd widget sets the variable `dir` to the path of the target directory before invoking `cd`. This causes zsh to treat the target directory as a named directory, which has the effect of zsh substituting '%~' with '~dir' instead of the proper path when it performs prompt expansion.
This commit will cause the widget to unset `dir` before redrawing the prompt to fix this issue.
Details of zsh prompt expansion can be found in:
http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html
1. Start a zsh session.
2. Configure the prompt by running `PROMPT='%~%# '`
3. Run the cd widget and select a directory (e.g., `~/destination`)
The prompt would be shown as `~/destination%`.
The prompt is shown as `~dir%`.
> zsh: prevent the current directory from appearing as `~dir` in prompts

- shell/completion.bash
- shell/completion.zsh
This commit fixes a bug where lines that declare multiple hostnames get
omitted from completion entirely if one of the hostnames matches *. For
example:
Host foo.com bar.dev baz.*
> ssh completion: skip only aliases matching *

- plugin/fzf.vim
Add &shellcmdflag and TERM environment variable treatment.
- Make &shellcmdflag `/C` when &shell turns into `cmd.exe`
- Delete %TERM% environment variable before fzf execution
On MSYS2 environment, vim is typically configured as follows:
- &shell: bash
- &shellcmdflag: -c
- $TERM(%TERM%): xterm or something
Since this plugin does not change &shellcmdflag while it replaces &shell with cmd.exe,
vim on MSYS2 environment cannot start fzf properly.
(It try to do `cmd.exe -c something...` but it should be `cmd.exe /C something...`.)
And at the time of starting cmd.exe %TERM% is no longer needed.
So delete this environment variable in the batch file to be executed.
> Add MSYS2 support as a vim plugin

- plugin/fzf.vim
Truecolor does not work on default Windows terminal.
It is a problem in neovim GUIs.
https://github.com/sainnhe/edge/issues/5#issuecomment-565748240
> [vim] use cterm colors on Windows

- plugin/fzf.vim
Followup on https://github.com/junegunn/fzf/commit/f68017d21e78b23fbf648d579edb6500ae7a6de8#commitcomment-36437403
After this, all `fzf.vim` commands must be updated to not use truecolor formatting on Windows. Need more testing to verify if `iconv` is really needed. Maybe it's required for (g)vim only.
> [vim] Encode list source to codepage

- README.md
- shell/key-bindings.bash
Enables the right bindings when switching between editing modes.
Fixes #39
> [bash-completion] Populate emacs and vi keymaps

- shell/completion.zsh
This PR fixes issues derived from quoting and word-splitting in Zsh completion.
Since `fzf-completion` calls `eval` without carefully quoting `$lbuf`, it broke in the following situation.
First, type:
```zsh
telnet -l "User that is quoted" **<TAB>
```
and hit <kbd>enter</kbd> to select `localhost` resulted in:
```zsh
telnet -l Userlocalhost
```
whereas the correct behaviour should be:
```zsh
telnet -l "User that is quoted" localhost
```
Simply quote the parameter using `${(q)lbuf}` solves this issue.
`_fzf_complete` splits its parameter (`$1`) in order to pass them to `fzf` in shell manner; however, the way it does this is not exactly the same way as Zsh. For instance, let's say we want to pass a parameter that contains spaces as follows:
```zsh
_fzf_complete '--tiebreak index --preview …
```
> [zsh-completion] Fix quoting/splitting issues

- .gitignore
- README.md
- src/terminal.go
fix #1637 
```
SHELL=kaka go run .  --preview 'cat {}'
```
[preview window is empty]
Preview window:
```
exec: "kaka": executable file not found in $PATH
```
test suite pass
```
make test > /dev/null && echo $?                                   
0
```
```
138   go run .  --preview 'cat {} |grep fzf'
149   go run .  --preview 'cat {} |grep -v fzf'
152   go run .  --preview 'cat {} |grep -v fzf'
```
> fix issue #1637 show error message when preview command fails

- src/options.go
```zsh
fzf --jump-labels="아" --bind='ctrl-s:jump'
```
will correctly warn the non-ascii character with with message `non-ascii jump labels are not allowed`
---
When I was working on https://github.com/junegunn/fzf/pull/1844, a minor bug was found, so I opened this PR separately, cause the PR https://github.com/junegunn/fzf/pull/1844 is `feature` PR.
If this bug-fix should be included in https://github.com/junegunn/fzf/pull/1844, please feel free to close it 👍
> Fix bug of validation of jump-labels

- man/man1/fzf.1
- shell/completion.bash
- src/options.go
- src/options_test.go
- src/terminal.go
- test/test_go.rb
Thank you for developing and maintaining this state-of-the-art CLI.
I opened this PR because as well as prompt, pointer sign and selected signs (in multi-select mode) should also be customizable with command line arguments.
Such feature, for example, would be useful in a case, where UI-provider really want users to know "WHAT" will happen ( `multi-delete` :fire: or `multi-star` ⭐️ ) with emoji.
> Make pointer and selected sign customizable

- .travis.yml
- shell/key-bindings.bash
- test/test_go.rb
Be consistent with emacs mode and put the items at the point vs. the end
of the command line.
> [bash] Put C-t items at point in vi mode

- shell/key-bindings.bash
Make <kbd>C-t</kbd> more consistent pre and post Bash 4. It already kills the
command line separately before and after the insertion point. Add
[`set-mark`](https://www.gnu.org/software/bash/manual/bash#index-set_002dmark-_0028C_002d_0040_0029) and [`exchange-point-and-mark`](https://www.gnu.org/software/bash/manual/bash#index-exchange_002dpoint_002dand_002dmark-_0028C_002dx-C_002dx_0029) to restore the insertion point
after yanking back and apply the same behavior to <kbd>M-c</kbd>.
> [bash] Restore insertion point pre Bash 4

- shell/key-bindings.bash
I updated #1817 to work on macOS, and replaced --tac --sync with fc -r. Would you consider giving it another review?
> [bash] Multiline C-r without histexpand

- man/man1/fzf.1
- src/options.go
- src/terminal.go
- test/test_go.rb
Action 'backward-delete-char-non-empty' will either abort if query if empty or delete one character backwards.
This is more geared towards something like [zsh-interactive-cd](https://github.com/changyuheng/zsh-interactive-cd), where pressing backspace on an empty query is the (at least my) natural tendency when you want to exit out of fzf.
This would partially resolve changyuheng/zsh-interactive-cd#5.
Also partially resolves #1797 . Doesn't implement the long-press repetition request though.
> feat: Add action for backspace if query empty

- .travis.yml
- shell/key-bindings.bash
- test/test_go.rb
Retain the current command line when aborting <kbd>C-r</kbd>. Add `--query
"$READLINE_LINE"` and fall back to the current behavior pre Bash 4.
Fixes #432
Fixes #731
> [bash] Start C-r search with current command line

- README-VIM.md
- man/man1/fzf.1
Getting my vim colors to work with  fzf was quite a challenge. After some experimentation and "code diving" I think I've made sense of it. Adding some notes on this to the README-VIM file that may help others facing similar issues.
> Add explanation for the `g:fzf_color` vim setting

- shell/completion.zsh
- test/test_go.rb
This PR fixes a bug in `_fzf_complete` in Zsh completion where it did not iterate through its arguments due to the usage of `ksh_arrays`.
See below as to how `ksh_arrays` changes the expansion behaviour in `$#foo` where `foo` is the name of an array.
```zsh
foo=(a b c d e f g)
echo $#foo      # => 7 (the number of elements in foo)
echo ${#foo[@]} # => 7 (the number of elements in foo)
```
```zsh
foo=(a b c d e f g)
echo $#foo      # => 1 (the number of characters in the first element of foo)
echo ${#foo[@]} # => 7 (the number of elements in foo)
```
As a result, `_fzf_complete` only works as expected either when `--` is the first argument passed to `_fzf_complete` or when `--` appears at the position in which it is less than the number of characters of the first argument to …
> [zsh-completion] Fix a bug where _fzf_complete did not iterate through args

- src/util/atomicbool.go
It's very straightforward to use _actual_ atomic instead of mutex. And it's paying off in nearly 10x margin in terms of performance
```
goos: linux
goarch: amd64
pkg: github.com/junegunn/fzf/src/util
BenchmarkMutex_Set-4            20000000                69.4 ns/op
BenchmarkMutex_Get-4            20000000                68.9 ns/op
BenchmarkAtomic_Set-4           200000000                7.66 ns/op
BenchmarkAtomic_Get-4           2000000000               0.42 ns/op
```
> 10x faster AtomicBool implementation

- shell/completion.zsh
- shell/key-bindings.zsh
At the top of each zsh file options are set to their standard values (those marked with `<Z>` in `man zshoptions`) and `aliases` option is disabled.
At the bottom of the file the original options are restored.
Fixes #1938.
> [zsh] Ensure that fzf code always parses the same way

- plugin/fzf.vim
This PR tries to fix the issue #1916.
Here is the purpose of each change:
-  return {'tab': tabpagenr(), 'win': winnr(), 'cnt': winnr('$'), 'tcnt': tabpagenr('$')}
+  return {'tab': tabpagenr(), 'win': winnr(), 'winid': win_getid(), 'cnt': winnr('$'), 'tcnt': tabpagenr('$')}
Inside `fzf.on_exit()`, this test wrongly succeeds when fzf has been invoked from a popup terminal:
if s:getpos() == self.ppos
This is because a popup window does not have a number and `winnr()` always evaluates to 0 in a popup terminal.  By including `win_getid()` in the dictionary, the test correctly fails when fzf is invoked from a popup terminal.
---
+        if !has('nvim') | call term_sendkeys(bufnr('#'), "exit\<cr>") | endif
This line terminates the `sh` job bound to the `!sh` terminal buffer which [was …
> fix issue #1916

- README.md
- bin/fzf-tmux
- man/man1/fzf-tmux.1
- shell/completion.bash
- shell/completion.zsh
- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
- test/test_go.rb
Requires latest tmux built from source (e.g. `brew install tmux --HEAD`)
Examples:
```
fzf-tmux -p
fzf-tmux -p80%
fzf-tmux -p80%,40%
fzf-tmux -w80% -h40%
fzf-tmux -w80% -h40% -x0 -y0
```
You can configure key bindings and fuzzy completion to open in tmux
popup window like so:
```sh
FZF_TMUX_OPTS='-p 80%'
```
Screenshot:
Issues with tmux popup window:
- Not mature
- Rendering isn't as efficient
- ~~Mouse doesn't work~~ ([works](https://github.com/tmux/tmux/issues/1842#issuecomment-607129692))
> [fzf-tmux] Add option to start fzf in tmux popup window

- README.md
It is not clear from the description that you might have to manually install it, especially on LTS Ubuntu
> Add more details on apt installation in README.md

- .travis.yml
- test/test_go.rb
What do you think of adding minitest assertions, to improve the automated tests output?
```
1) Error:
TestZsh#test_process_completion:
RuntimeError: timeout
test/test_go.rb:47:in `wait'
test/test_go.rb:118:in `until'
test/test_go.rb:2025:in `test_process_completion'
```
```
1) Failure:
TestZsh#test_process_completion [test/test_go.rb:2047]:
Expected: "kill 16358"
Actual: "kill 1"
```
> Improve error messages

- shell/key-bindings.zsh
s///r is only available since perl 5.14. The perl oneliner
was changed to work with older perls, possibly even with 5.000.
> compat with older perls

- plugin/fzf.vim
I propose to use pty-buffer instead of unnecessary shell process when opening popup window.
> [vim] Don't start extra process at opening popup

- bin/fzf-tmux
When using fzf with tmux popup window options, rendering in vim is broken.
The cause seems to be in this [approach](https://github.com/junegunn/fzf/pull/433). 
Before fix
After fix
> Fix rendering in vim is broken with zoomed tmux.

- README.md
From the bat man page:
```
-r, --line-range <N:M>...
Only print the specified range of lines for each file. For example:
--line-range 30:40
prints lines 30 to 40
--line-range :40
prints lines 1 to 40
```
I think this should be more efficient than head? 
And either way, it is the proper way, better to make it easy to find because it took me some time to find it :sweat_smile: 
Also, why 500 lines? What insane terminal is that where you can see 500 lines vertically without scrolling? ^^
> README: Use --line-range instead of head in bat example

- install.ps1
If a user has the Powershell Community Extensions installed, it comes
with another command Expand-Archive that doesn't have a DestinationPath
argument, causing an error during installation:
```
Expand-Archive : A parameter cannot be found that matches parameter name 'DestinationPath'.
At W:\env_config\.vim\plugged\fzf\install.ps1:60 char:33
+     (Expand-Archive -Path $temp -DestinationPath .); (Remove-Item $te ...
+                                 ~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Expand-Archive], ParameterBindingException
+ FullyQualifiedErrorId : NamedParameterNotFound,Pscx.Commands.IO.Compression.ExpandArchiveCommand
```
Note the last line, `Pscx.Commands.IO.Compression.ExpandArchiveCommand` indicates that Powershell tried to use the wrong …
> Fully qualify Expand-Archive

- README.md
[XBPS](https://voidlinux.org/usage/xbps/) is the package manager of [Void Linux](https://voidlinux.org/)
the package can be found by searching it via the [Void Packages](https://voidlinux.org/packages/) website "fzf" (unable to provide direct URL)
> Void Linux installation instructions

- README.md
Nix can be installed on (almost) any Linux distro and on macOS.
See https://nixos.org/nix/ for more information.
> README: Correct Nix distro support

- plugin/fzf.vim
I use ```autocmd BufEnter * silent! lcd %:p:h``` as suggested in this document <https://vim.fandom.com/wiki/Set_working_directory_to_the_current_file>.
When the '--multi' flag is set and I try to open multiple files, the current directory is changed after the first file is opened, which results in the following files failed to open because of the filenames are relative paths to "current directory".
I think this solution covers both 'autochdir' and 'BufEnter lcd' scenarios.
> preserve current directory in case someone changes it

- plugin/fzf.vim
When restarting fzf from the fzf sink function, depending on the timing, w:fzf_pushd unlet fails and an error occurs.
I changed `unlet` to `unlet!` and the problem was solved.
Error message:
```
Error detected while processing function 140[30]..<SNR>23_callback[28]..<SNR>23_dopopd:
line   24:
E108: No such variable: "w:fzf_pushd"
```
OS: macOS Catalina 10.15.5
Shell: zsh
Editor: neovim (NVIM v0.5.0-nightly-348-g1ca67a73c)
> Fixed failure of w:fzf_pushd unlet depending on timing

- go.mod
- go.sum
- src/tui/light.go
- src/tui/light_unix.go
- src/tui/light_windows.go
- Update to latest tcell (1.4.0) which added 24 bit color Windows support
- light renderer under Windows defaults to Dark256, if possible
- Turns off Windows truecolor support if TCELL_TRUECOLOR is set to 'disable'
> Add truecolor support for Windows, if available

- shell/key-bindings.zsh
Fix the regular expression to capture the command containing asterisk.
After [this commit](https://github.com/junegunn/fzf/commit/e6d33f77da8cc36786c814f499f6cb3405e8c4c1#diff-961174188263ff616f70beae85ee0763), CTRL-R command history search has failed to display some commands in zsh.
The new method to cut the history number from the each line can't capture the command containing an asterisk(*) mark followed by the number.
If you have command history like an example below, CTRL-R only displays `ls`, `vi`, `man`, `git` and `ssh`... .
`$ fc -rl 1` output example
```shell
123* ls
122* cd
121* date
120 vi
119 man
118* git
117* which
116* emacs
115 ssh
...
```
I have little knowledge about perl, but I guess when it processes the `123* ls` line, capturing failure makes `'undef'` hash key. So the …
> [zsh] Fix regular expression in history search function

- src/terminal.go
This fixed width limit bug #2189 :
> Fix items width limit

- shell/key-bindings.zsh
We need directory movement history to look back at work history while reading zsh_history.
This keeps history by accepting the line where 'cd "$dir"' is written.
> Record cd execution in history

- CHANGELOG.md
- man/man1/fzf.1
- src/options.go
- src/terminal.go
Hi @junegunn,
Awesome command. It took me one week-end to learn but I can jump anywhere.
I would personally like to jump half screen in the preview window (like ctrl-d in vim), actually I map it to  alt-d.
__This PR does not change the default behavior.__
-----
Well it's just like jumping a full screen divided by two but to follow french courtesy, I join a screencast where I 1/2 press alt-d and then ald-u
> Feature: Add action preview-half-page-down

- shell/completion.bash
- shell/completion.zsh
Having multiple ssh config files with no empty line at the end of file causes some host to be missing. This is due to `cat` merely merge all the files content without any delimiter. E.g.
// a
Host A
HostName x.x.x.x<EOF>
// b
Host B
HostName y.y.y.y<EOF>
Will only return either A/B.
> Fix missing ssh host

- shell/key-bindings.fish
Fixes error when option-like args are parsed (e.g. "-1", followed by `c-t` to trigger fzf).
> [fish] Fix parser handling of option-like args

- CHANGELOG.md
- README.md
- src/constants.go
- src/terminal.go
- src/tui/dummy.go
- src/tui/light.go
- src/tui/tcell.go
- src/tui/tui.go
Preliminary implementation of the streaming preview window. Please test and report any bugs. Fix #2212.
```sh
fzf --preview 'for i in $(seq 100); do echo $i; sleep 0.01; done'
fzf --preview 'sleep 1; for i in $(seq 100); do echo $i; sleep 0.01; done'
fzf --preview 'date; sleep 2; date'
rg --line-number --no-heading --color=always ^ |
fzf --delimiter : --ansi --preview-window '+{2}-/2' \
--preview 'sleep 1; bat --style=numbers --color=always --pager=never --highlight-line={2} {1}'
```
/ping @p-kolacz @edi9999
> Implement streaming preview window

- plugin/fzf.vim
OS : Windows10
vim : gvim 8.2
This pull request is fixed candidate's text with Multibyte language(exe. Japanese).
> Fix: barbled multibyte text(exe. Japanese).

- shell/completion.bash
Commit d4ad4a25 slowed loading of completion.bash significantly (on my
laptop from 10 ms to 30 ms), then 54891d11 improved that (to 20 ms) but
it still stands out as the heavy part of my .bashrc. Furthermore, an
omission in d4ad4a25 caused meaningless "complete _a" and "complete _v"
completions to be defined.
This pull request fixes that mistake, refactors the code to prevent
making it again, and most importantly optimizes
__fzf_orig_completion_filter so that loading completion.bash is as fast
as it was before d4ad4a25, that is under 10 ms on my laptop.
(I tried not to use any features not present in bash 3.2, but I didn't
test it with bash 3.2. Can someone try this on MacOS please?)
> [bash-completion] Optimize startup + two minor fixes

- shell/completion.bash
I forgot to add the "not _fzf" check into __fzf_orig_completion, so
invoking it twice would rewrite the _fzf_orig_completion_xxx variables
and then cause an endless loop when completion is requested.
Fixes: https://github.com/junegunn/fzf/pull/2246
Reported-by: @wingpin6
> [bash-completion] Fix endless loop when completion.bash sourced twice

- plugin/fzf.vim
The clean-up is done in s:collect(), so let's make sure it's run before
we may terminate due to CTRL-C or ESC in exit_handler().
> [vim] Clean up temp files on interrupt

- shell/key-bindings.zsh
Zsh with option `WARN_CREATE_GLOBAL` helps find bugs like this. Basically, builtin `read` assigns to whatever variable it is given, and by default when variable does not exists — it will be created in global scope, but in my case (with option turned on) it produces a warning:
```
__fsel:6: scalar parameter item created globally in function __fsel
```
> zsh: declare variable as local before assignment

- shell/key-bindings.zsh
When history sharing across shells is enabled (`setopt SHARE_HISTORY`), history written by shell A won't be available in shell B until re-rendering the prompt in B (e.g. by pressing Enter at the prompt).
With this change, C-r will always reload the history file if history sharing is enabled, making the latest history searchable immediately.
> [zsh] Reload shared history before searching

- shell/key-bindings.zsh
Fix for #2101 
zsh sends SIGCONT when running fzf in a pipe in certain cases, causing mouse mode to become disabled when using the ctrl-r and alt-c keybindings in zsh.
Work around this problem by using redirection instead.
The zsh completion scripts are already doing this (e.g. https://github.com/junegunn/fzf/blob/master/shell/completion.zsh#L219).
> #2101 keep mouse mode in ctrl-r, alt-c in zsh

- src/options.go
This fixes the following errors with Go 1.15:
```
src/options.go:452:69: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
src/options.go:463:33: conversion from untyped int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
> Use more explicit int-to-string conversion.

- src/terminal.go
Before:
If cursor placed at the end of list (i.e. maximum offset):
https://user-images.githubusercontent.com/8470556/103484891-3f5f2300-4e03-11eb-9f54-3a5eb5e7a0e5.mp4
After:
https://user-images.githubusercontent.com/8470556/103484901-57cf3d80-4e03-11eb-813b-af8272ad44ee.mp4
> Fix selection changed on terminal resize

- README.md
Unless there is some specific reason that FZF needs to be reinstalled, running brew update and then brew upgrade will upgrade all formula, including FZF. Reinstalling does not seem necessary for this use case and makes it seem as if users need to go to the additional step of reinstalling FZF when the usual brew upgrade and then brew install workflow will work correctly to upgrade FZF. However, if I have missed some specific reason why FZF needs to be reinstalled, I'll close this PR accordingly. Open to comments!
> Update README to upgrade using brew upgrade

- shell/completion.zsh
Fixes #2317.
It seems `zle reset-prompt` doesn't work correctly inside `eval`.
> Fix zsh completion

- plugin/fzf.vim
Mode is global, therefore if we close the FZF window without quitting terminal mode (the current behavior), we enter the next buffer in terminal mode. If the next buffer happens to be a terminal, we are unexpectedly in terminal mode even if we left it in normal mode. This is especially annoying when using the `:Buffers` command of fzf.vim to switch to a terminal buffer.
This behavior is explained in [neovim#13769](https://github.com/neovim/neovim/issues/13769) and this PR fixes [fzf.vim#1216](https://github.com/junegunn/fzf.vim/issues/1216).
This affects only Neovim since it seems that Vim always exits terminal mode (but it's Vim that is not consistent in that case).
> Exit terminal mode before closing FZF window in Vim/Neovim

- install.ps1
The first version of install.ps1 was created by me on last pull request on last year. But the original implement of it was missing the feature to set the access right of fzf.exe. It may cause the following issue:
1. Failed to run "fzf --version": ['<be><f8><b7><c3><ce>?<a3>^M']",  Please see issue #2256.
2. Failed to download fzf.exe because it will delete fzf.exe if the return result of "fzf --version" is wrong, see point 1.
Also,  the download progress hasn't been showed at previous implmentation. Ths pull request also fixed this.
> Fixed the issue of "Failed to run fzf --version: [<be><f8><b7><c3><ce>?<a3>^M]"

- BUILD.md
Latest Go 1.11 not working
```sh
$ make
src/options.go:463:9: undefined: strings.ReplaceAll
note: module requires Go 1.13make: *** [Makefile:122: target/fzf-linux_amd64] Erro 2
```
> Update build dep **Go**

- man/man1/fzf.1
On my GNU/Linux system `$SHELL` --if set-- is used for fzf's `execute` action and preview and default commands.
Consider the following example of a script portability issue due to using `SHELL`:
```sh
SHELL=/usr/bin/fish FZF_DEFAULT_COMMAND="foo() { ls; }; foo" fzf
```
_More typically, `SHELL` is set in a user's shell profile file`._
`$FZF_DEFAULT` will fail because `foo() { ls; }; foo` is invalid fish syntax although it is valid for a POSIX shell.
Setting `SHELL=` above or using `env -u SHELL` will fix the problem.
Deleting `SHELL=...` altogether will leave fzf's command executor undefined--either `$SHELL` or `/bin/sh`.  This is the portability issue I mentioned.  It's unlikely to happen but it can happen.
The portability issue depends on the environment in which a script will run. …
> fzf.1 clarify that $SHELL is used to run commands

- shell/key-bindings.zsh
`precmd` hooks expect the Zsh Line Editor to not be active.
Running these when the ZLE is active can lead to unpredictable results.
See https://github.com/marlonrichert/zsh-autocomplete/issues/180
> Don't run precmd hooks in cd widget

- plugin/fzf.vim
I noticed that some `border` related sources codes have been left in Neovim's `create_popup` function.
I think that from [this commit](https://github.com/junegunn/fzf/commit/2e8e63fb0b3b62e89472eebe9e86578598e1a541), `border` had been fully controlled by `fzf` binary itself, and script-local `s:create_popup` function is never been called against `opts` with `border` property.
> [vim] Remove unnecessary `border` management in nvim floating window

- plugin/fzf.vim
Note that this is an exact duplicate of #1621, I ran into the issue again but couldn't reopen as I've since deleted the fork.
This time I have reliable steps to reproduce:
1. Create a directory containing three files, `a`, `b` and `c`.
2. Run `vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)`.
3. Execute `let g:fzf_layout = { 'window': 'enew' }`.
4. Execute `clearjumps`. Output of `jumps` is now an empty jump list. This is correct.
5. Execute `FZF` and select file `b`. Output of `jumps` now contains one entry, the position in `a`. This is still correct.
6. Execute `FZF` and select file `c`. Output of `jumps` now contains two entries, the position in `a` and the position in `b`. However, the entry in `a` has index `3`, and the entry in `b` …
> [vim] Use keepjump (again)

- bin/fzf-tmux
[In a latest change](https://github.com/tmux/tmux/commit/c44750792a9683c5cd6f9df5a69e7417b88772d2), tmux deleted `-K`, `-R` flags to `display-popup`, `popup` command.
This PR updates `fzf-tmux` script to add support for new version .
> [fzf-tmux] Adapt to tmux latest changes

- shell/key-bindings.fish
Currently, when having a commandline like `grep --exclude-from=~/Desktop`  using the `fzf-file-widget` does not work since it takes `--exclude-from=` as part of the path.
This PR makes the widget under fish shell work even when the path is prefixed with an option.
> fish key bindings: make fzf-file-widget work with -option= prefix

- Makefile
- src/ansi.go
- src/ansi_test.go
This commit speeds up the parsing/processing of ANSI escape codes by roughly 7.5x. The speedup is mostly accomplished by replacing the regex with dedicated parsing logic ([`nextAnsiEscapeSequence()`](https://github.com/charlievieth/fzf/blob/3d4a123fa2c7f4daf9dc822fbc3e52214172d106/src/ansi.go#L122-L184)) and reducing the number of allocations in [`extractColor()`](https://github.com/charlievieth/fzf/blob/3d4a123fa2c7f4daf9dc822fbc3e52214172d106/src/ansi.go#L186-L276).
```
name             old time/op    new time/op     delta
ExtractColor-16    4.89µs ± 5%     0.64µs ± 2%   -86.87%  (p=0.000 n=9+9)
name             old speed      new speed       delta
ExtractColor-16  25.6MB/s ± 5%  194.6MB/s ± 2%  +661.43%  (p=0.000 n=9+9)
name             old alloc/op   new alloc/op    delta …
```
> ansi: speed up parsing by roughly 7.5x

- README.md
Since --phony was renamed to --disabled in 
https://github.com/junegunn/fzf/commit/d779ff7e6dcf068fbcf743bed45127c3b857ec92 
it makes sense to update the README accordingly ;)
> Update README (--phony -> --disabled)

- README-VIM.md
- doc/fzf.txt
- plugin/fzf.vim
Neovim supports a `relative` option in `nvim_open_win()` that allows you to position windows relative to the current window or the cursor (as opposed to the entirety of the editor).
This PR:
- passes all options from `s:popup` to `s:create_popup` so that it can receive `relative` (plus other options like `anchor`)
- uses window width/height instead of `&columns`/`&lines` if the `relative` option is present
A configuration of `let g:fzf_layout = { 'window': { 'relative': 'win', 'width': 1.0, 'height': 0.4 }}]` looks like this:
> Support relatively positioned windows in Neovim

- src/tui/light_windows.go
- restore VT enable hack;  this is restoring 2 lines of code that were removed in a previous commit of mine (https://github.com/junegunn/fzf/pull/2430/commits/281f9982acef2d3dfcb68545cee2383f0d29ad3f)
- resolves an issue reported in kelleyma49/PSFzf#84
> Restore VT hack for Windows

- src/ansi_test.go
- src/tui/tcell.go
This is few minor things I came across lately.
- fmt.Println in tests doesn't honor verbosity flags like t.Log does
- the keyboard event works just fine for space character
> Minor changes

- src/ansi_test.go
**1. Fixed just a minor spelling error**
`ansiRegexRefence` → `ansiRegexReference`
**2. I found some links in source code broken, so  replaced them with the archived ones.**
- http://ascii-table.com/ansi-escape-sequences.php
- http://ascii-table.com/ansi-escape-sequences-vt-100.php
↓
- https://web.archive.org/web/20090204053813/http://ascii-table.com/ansi-escape-sequences.php
- https://web.archive.org/web/20090227051140/http://ascii-table.com/ansi-escape-sequences-vt-100.php
> Fix spelling and broken links

- src/tui/tcell.go
- src/tui/tcell_test.go
- src/tui/tui.go
- src/util/util.go
This pull request is focused on fixing some issues and adding new features in the FullscreenRenderer. Most of the branch is about keyboard events, but the last commit also implements mouse events.
Keyboard
-----------
- I tried to bring the keyboard events in FullscreenRenderer as close as possible to the LightRenderer
- additions:
- extensive testing of the tcell events that fzf uses as source for keyboard events
- ability to input AltGr characters on foreign keyboards
- fixes:
- CtrlSpace event didn't work
- CtrlCaret event wasn't implement
- there was big discrepancy in how backspace key is handled between FullscreenRenderer and LightRenderer. The CtrlH event was emitted even in the cases where BSpace or AltBS was appropriate.
Mouse
-------
The mouse events in LightRenderer are …
> Align keyboard and mouse support in FullscreenRenderer with LightRenderer

- .github/workflows/codeql-analysis.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
Hi, this enables manual trigger on your workflows. Documented [here][1].
This is useful for forks to run the checks/tests themselves (on their own account) in case of
- failure, to see full logs or verify reproducibility
- before sending pull request, or committing to PR (if one wants to see results beforehand)
Steps needed before this patch:
1. fork fzf
2. enable workflows for the fork (web ui)
3. push this patch in master
4. push this patch in feature branch
5. trigger workflow (web ui)
Steps needed after this patch:
1. fork fzf
2. enable workflows for the fork (web ui)
3. trigger workflow (web ui)
The annoying part is pushing the same patch in fork's master and feature branch. Also pushing workflow changes may require additional authorization, so fork dev may need to generate new …
> Enable manual trigger on GitHub Workflows

- src/terminal_test.go
- src/terminal_windows.go
- src/util/util_windows.go
> Fix powershell escaping

- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
Otherwise directories starting with '-' may treated as options.
> [shell] Use cd --

- .github/workflows/codeql-analysis.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrade based on SHA.
Signed-off-by: naveensrinivasan …
> Pin actions to a full length commit SHA

- shell/key-bindings.bash
This makes it easier to make customizations, for example instead of
bind -x '"\C-o\C-i": FZF_CTRL_T_COMMAND="fasd -Rl" FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --tiebreak=index " fzf-file-widget'
it's enough to just
bind -x '"\C-o\C-i": FZF_CTRL_T_COMMAND="fasd -Rl" fzf-file-widget --tiebreak=index'
> Allow passing args to __fzf_select__ via fzf-file-widget

- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
Ever since https://github.com/junegunn/fzf/pull/2659 was merged, the ALT-C command completes to `cd -- /selected/path`.  The `--` was added to prevent directories starting with `-` from being treated as options.
However, this also creates problems for people using tools like [zoxide](https://github.com/ajeetdsouza/zoxide) to replace their `cd` command (https://github.com/ajeetdsouza/zoxide/issues/332). A more correct approach would be to use `builtin cd`.
> [shell] use builtin cd to avoid conflicts

- plugin/fzf.vim
`shellescape()` behaviour different when `shell=fish`, so we should set `shell` before calling `shellescape()`, otherwise some wired behaviour (such as https://github.com/kevinhwang91/nvim-bqf/issues/56) may apper.
> Fix fzf#shellescape when shell=fish

- install
There is no use exporting PATH when it is already exported. Moreover, it
causes things like `typeset -U path` in zsh to break if done before
sourcing "~/.fzf.zsh".
> Don't export PATH in ~/.fzf.{bash,zsh}

- Makefile
Add loongarch64 support. Golang has supported [linux/loong64](https://github.com/golang/go/commit/ec464edb22301764b6caf7592ac8dc9451c595c6)
- golang: https://github.com/golang/go/tree/master
- os: https://github.com/sunhaiyong1978/CLFS-for-LoongArch/releases/download/4.0/loongarch64-clfs-system-4.0.tar.bz2
```
[root@upstream fzf]# make
GOARCH=loong64 go build -a -ldflags "-s -w -X main.version=0.30.0 -X main.revision=7052987" -tags "" -o target/fzf-go1.19-351e0f4083_loong64
[root@upstream fzf]# file target/fzf-go1.19-351e0f4083_loong64 
target/fzf-go1.19-351e0f4083_loong64: ELF 64-bit LSB executable, LoongArch, version 1 (SYSV), statically linked, Go BuildID=5iDziOizZrrXAzlds9wq/M5acTdJilXLFpQTMGG8n/k1KhML9cEvrnfvJIKIse/-N-KbgmUR6MODVFxdzZZ, stripped
```
> Add loongarch64 support

- shell/completion.bash
this isn't the _full_ fix but I left an inline comment in case this ever
bugs a future user and they're wondering where the last few flags'
completions are (answer: they're not added yet, as they're just
diminishing return for _this_ particular quick itch-scratching).
> fix `fzf-tmux` to have `fzf`'s completion

- shell/key-bindings.zsh
Unlike awk, which is even defined in POSIX, perl is not pre-installed on all *nix systems. This awk command is functionally equivalent to the original perl command.
~~If extended_history is enabled, the history widget will display:~~ (EDIT: rejected)
~~12  2022-04-02   echo "older command"~~
~~123  today'16:30  echo "today's command"~~
> [zsh] Replace perl with awk

- plugin/fzf.vim
- Replace fzf#shellescape with shellescape as it was surround the command in "^" characters that powershell did not recognise as escape characters
- Prepend command with '&' in powershell to deal with quoted exe name
> Fix version check on windows/powershell

- shell/completion.bash
I opened #2474 more than a year ago and came to the conclusion that it was more [bash-completion's](https://github.com/scop/bash-completion) fault than fzf's. However, it does not appear it's an easy fix in bash-completion, and it's a fairly easy fix in fzf. It also appears other people are running into it (ex: #2583) - I, myself, just ran into it again on a new machine - so maybe we should just fix it?
Open to other suggestions. This PR is my proposal from the ticket long ago =)
> fixes #2474 bash completion: possible retry loop

- shell/key-bindings.zsh
Currently `fzf-history-widget` simply shows duplicated candidates, because unlike GNU awk `\s` is not supported by Apple's awk.
This PR fixes this issue by modifying regex so that it works with both GNU and macOS awk.
```sh-session
$ echo '123  hello' | awk '{ sub(/^\s*[0-9]+\s+/, "", $0); print $0 }'
123  hello
$ echo '123  hello' | awk '{ sub(/^[ \t]*[0-9]+[ \t]+/, "", $0); print $0 }'
hello
$ awk --version
awk version 20200816
```
> [zsh] Fix the problem command history deduplication not working on macOS

- CHANGELOG.md
- bin/fzf-tmux
Before this PR, inside tmux, `fzf-tmux -p` will show double border if fzf has already enabled its border
After this PR, we will check if we've enabled `--border` in `FZF_DEFAULT_OPTS`. If so, we can turn off tmux popup window border
> fzf-tmux: disable tmux popup window border if fzf has already enabled its border

- src/ansi.go
This commit slightly refactors the escape sequence matching functions
for a 20% speed up.
ANSI Benchmarks:
```
goos: darwin
goarch: arm64
pkg: github.com/junegunn/fzf/src
name                       old time/op    new time/op    delta
NextAnsiEscapeSequence-10     114ns ± 1%      90ns ± 1%  -21.57%  (p=0.008 n=5+5)
ExtractColor-10               544ns ± 0%     517ns ± 0%   -5.01%  (p=0.008 n=5+5)
name                       old speed      new speed      delta
NextAnsiEscapeSequence-10  1.09GB/s ± 1%  1.39GB/s ± 1%  +27.52%  (p=0.008 n=5+5)
ExtractColor-10             230MB/s ± 0%   242MB/s ± 0%   +5.27%  (p=0.008 n=5+5)
```
> ansi: speed up escape sequence parsing by ~20%

- shell/completion.bash
This PR fixes the following minor problem.
In bash completion, if an environment variable contains a newline, the completion list contains the value (not the name) of the variable. The same problem exists with aliases.
Ex)
```bash
$ export AAA="
aaa_line1
aaa_line2
"
$ unset **<TAB>
> < 91/91 (0)
> AAA
aaa_line1
aaa_line2
"
...
```
> Fix bash completion var or aliase containing newlines

- man/man1/fzf.1
Hi
While reading the description of the `--info` flag, it's not immediately obvious that the "finder info" is in fact the UI element representing the match counters.
Thanks
> doc(man): add a hint about which UI element is the finder info

- plugin/fzf.vim
Didn't see any issues addressing this problem, or any other pull requests. Should fix problems for Windows users that have a space in the plugin path.
> Update fzf#install to handle spaces on Windows

- shell/completion.bash
- shell/completion.zsh
- shell/key-bindings.bash
- shell/key-bindings.zsh
- test/test_go.rb
when `set -o nounset` is enabled
completion complains about these variables being unset:
`orig_var`
`__fzf_no_space_commands`
> Fix unbound variables in shell completion

- man/man1/fzf.1
Hello
By following through the codebase what the `opt.Unicode` flag was reaching, it turns out that the spinner is also what of the ui element impacted : https://github.com/junegunn/fzf/blob/master/src/terminal.go#L450-L455
```go
func makeSpinner(unicode bool) []string {
if unicode {
return []string{`⠋`, `⠙`, `⠹`, `⠸`, `⠼`, `⠴`, `⠦`, `⠧`, `⠇`, `⠏`}
}
return []string{`-`, `\`, `|`, `/`, `-`, `\`, `|`, `/`}
}
```
I thought it's worth mentioning this in the documentation.
Thanks
> doc(man): complete the definition of what --no-unicode impacts

- src/util/eventbox_test.go
Hi
The `EvtClose` constant was removed in 2017 in this commit refactoring the Reader : https://github.com/junegunn/fzf/commit/487c8fe88f4cfcc55850b8aef73665b1d09b8fe0
I was confused by finding this type of Event I didn't know about yet while executing this EventBox test-suite.
As it's not used in the code-base anymore, this obsolete event can be retired.
Thanks
> test(eventbox): remove obsolete EvtClose const

- README.md
At first I thought they were appended to FZF_*_COMMAND. Let's make it
clear that these are passed to `fzf` itself.
> README.md: clarify what FZF_*_OPTS is used for

- CHANGELOG.md
- man/man1/fzf.1
- src/options.go
- src/options_test.go
- src/server.go
- src/terminal.go
- test/test_go.rb
```sh
fzf --listen 6266
curl -XPOST localhost:6266 -d 'reload(seq 100)+change-prompt(hundred> )'
```
Feedbacks are welcome. Do you like it? Are you going to use it? What are you planning to do with this?
This will significantly increase the size of the binary (2.8MB to 5.7MB for darwin arm64). [UPX](https://upx.github.io/) might help with the issue. (However, https://github.com/upx/upx/issues/601)
* Using signals as suggested in #2019 
* Limited to only two bindings, SIGUSR1 and SIGUSR2
* No SIGUSR1 or SIGUSR2 on Windows
* Non-HTTP socket server or named pipes
* Less expressive and less extensible. We can extend the HTTP server to support other HTTP verbs in the future.
* Likely less binary size? Haven't confirmed.
* Portability issue
> Add --listen=HTTP_PORT option to receive actions

- README.md
It's a long time that users are supposed to use `apt` for everything rather than `apt-*`
> Correct package manager commands for apt

- CHANGELOG.md
- man/man1/fzf.1
- src/options.go
- src/terminal.go
- src/tui/light.go
- src/tui/tcell.go
- src/tui/tui.go
- test/test_go.rb
- Actions to update border-label and preview-label.
Use case:
Instead of using "prompt" to identify my command, I prefer to use border-labels. The problem is that I have re-bindings to change which commands I'm using, but I can't update the label identifier.
> Add "change-border-label" and "change-preview-label" actions

- shell/completion.bash
Bat is a common alternative to `cat`, it's even referenced multiple times in fzf docs. This makes `bat **` work by default.
> Add bat to bash autocomplete commands

- src/core.go
- test/test_go.rb
Fixed an issue where fzf could crash when using the height range option and either the --exit-0 or --select-1 options simultaneously.
When running the following command:
```
> echo "aaa
bbb" | fzf --height=~10% --exit-0
```
fzf's filtering interface displays 'aaa' and 'bbb' as candidates, but if the filtering string 'c' is entered, fzf will force quit and fail.
Normally, fzf's filtering interface should continue and the candidates should be narrowed down to zero.
Additionally, after launching fzf in the following way, entering 'a' to filter causes fzf to force quit in the same way.
```
> echo "aaa
bbb" | fzf --height=~10% --select-1
```
The source code in this section is the cause:
https://github.com/junegunn/fzf/blob/025aa3377342135f527d728574e59db4cb781292/src/core.go#L219-L229
If both …
> fix a bug of height range.

- plugin/fzf.vim
If you are using Powershell 7 under Windows (meaning you have `shell` set to `pwsh`), FZF will fail to run with the following error:
> Add check for powershell 7 users

- man/man1/fzf.1
- src/options.go
- src/tui/light.go
- src/tui/tcell.go
- src/tui/tcell_test.go
- src/tui/tui.go
- test/test_go.rb
Currently there is not option to bind ctrl-delete and shift-delete. As suggested by issue #3240, shift-delete could be used to bind "delete entry from history" as it is a common way to do so in other applications, e.g. browsers.
This, however, does only implement to use the key combination itself and does not assign a default action to any of them. This does enable to call one's all predefined actions. With the exec action this can expanded like the issue #3240 suggested.
If desirable, the key combinations could later get a default behavior.
I mainly wanted to use shift-delete like suggested in #3240. My approach would be to use the exec() action to build this functionality myself. I would not be comfortable deleting from the uses history due to expansion/escape issue and deleting too …
> Add key combinations for ctrl-delete and shift-delete

- CHANGELOG.md
- man/man1/fzf.1
- src/options.go
- src/terminal.go
- src/tui/light.go
- src/tui/tcell.go
- src/tui/tui.go
I saw that you recently added the block border and would like to introduce a thinblock border as well. It is using the symbols from https://www.unicode.org/charts/PDF/U1FB00.pdf Symbols for Legacy Computing, ONE EIGHTH BLOCK elements.
I searched for all places with `BorderBlock` and added `BorderThinBlock`. One thing to note about the symbols is that they a font specific, and may not exist or may not align perfectly depending on the font and terminal emulator. In the case of Kitty terminal, box drawings are handled by Kitty rather than the font so it appears correctly regardless of the font.
**MonaLisa font missing the corner symbols in Alacritty:**
**Iosevka font in Alacritty**
**Iosevka font in Wezterm**
**Iosevka font in iTerm2**
**MonaLisa font in Kitty**
MonaLisa Font: …
> Add new border style: 'thinblock'

- src/history.go
- src/history_test.go
- src/options_test.go
- src/terminal.go
- src/tui/ttyname_unix.go
This PR addresses the recent deprecations in Go 1.16. I replaced them to the suggested versions (some of these methods where already under the hood calling the correct methods).
> Fix deprecations of ioutil

- Makefile
armv8l is always 32-bit and should implement the armv7 ISA, so just use the same filename as for armv7.
> Makefile: build 32-bit binary on armv8l

- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
- src/constants.go
`find`’s `-path`-option is described to use shell patterns (i.e. POSIX’ pattern matching notation).
In that, `.` is not a special character, thus escaping it shouldn’t be necessary.
> [shell] don’t needlessly escape `.` in shell pattern

- shell/completion.bash
Again... someone should thoroughly double check these, especially I have no `bash` versions from the primordial times of the universe around. ;-)
Speaking of which... does it really make sense to keep code for `bash` versions < 4? I mean bash 4 was something like early 2009.<br>
I'd just drop all code for those ancient versions, especially as all the use of `\C-b\C-k`, etc.  may anyway easily break, if a user has re-assigned them to something else.
> Various bash improvements

- shell/key-bindings.bash
* Use the all-compatible mawk `-W version` option. https://github.com/junegunn/fzf/pull/3313#issuecomment-1747934690.
* Do not remap the history key if no dependent commands is installed (perl, awk or mawk in this order).
* Run the command and not a function consistently with #3462.
The version check bash code relies on the following mawk source code, extracted from mawk 1.3.4 20230322.
```
version.c:
18-  #include "init.h"
19-  #include "patchlev.h"
20-
21:  #define	 VERSION_STRING	 \
22-    "mawk %d.%d%s %s\n\
23-  Copyright 2008-2022,2023, Thomas E. Dickey\n\
24-  Copyright 1991-1996,2014, Michael D. Brennan\n\n"
....
30-  void
31-  print_version(FILE *fp)
32-  {
33:      fprintf(fp, VERSION_STRING, PATCH_BASE, PATCH_LEVEL, PATCH_STRING, DATE_STRING);
34-      fflush(fp);
35-
36- …
```
> [shell] improve mawk detection

- shell/completion.bash
- shell/completion.zsh
- shell/key-bindings.bash
- shell/key-bindings.zsh
This should fix #3445 and bring some further minor cleanups.
As for the last commit of this series, which removes the interactiveness checks from the completion scripts and your comment:
> Fair enough. Please note that fzf can be installed by manually cloning the repo, so the files can be placed anywhere the user wants and they can make any mistake they want :)
over in #3445:<br>
I'd guess most people will install software via some form of packaging, which takes care of that - after all that's what the whole distros-system in *nix/BSD/Linux is there for.<br>
If someone installs manually from the sources, well than I think one can reasonably expect him to know what he's doing - or at least to live with it, when doing stupid things.
After all, we can only do so much to prevent people from …
> Improve interactiveness checks

- shell/completion.bash
Well, I tried to find out all possible options and "fixed" values as good as I could from the actual parsing code.<br>
Unfortunately both, `--help`-output and the manpage seem to be also outdated (see #3470), so these were couldn’t really be used as a reference.
Yeah,... I remember your comment in https://github.com/junegunn/fzf/issues/3457#issuecomment-1741704506 ... but it sounded rather unclear whether/when you'd go that "cobra"-way... and I don't want `fzf`’s own completion to be dropped.<br>
So here's an update.
That being said, I still think we should do #3457, but maybe we can discuss that in terms of some larger ideas.
btw:<br>
Why are you doing this:
https://github.com/junegunn/fzf/blob/a0d61b4c373f6b977314f7ebe53f6236798151e9/shell/completion.bash#L123-L126
?
Can it be dropped?
> [bash] bring fzf’s own bash completion up to date

- shell/completion.bash
- shell/key-bindings.bash
Hey.
This would be for #3458.
- The current commit (hopefully) adds `command ` to all commands that are not built-ins or functions.<br>
I haven't really tested it yet ;-) ... and guess anyway that it will be rather quite some effort to test all cases where `command ` is now used.
- A future commit might use `builtin` to protect further things like `printf` or `echo`. But arguably, it's always a trade off how far we go here (code readability vs. actually adding some benefit).
But I do think, that at least "regular" (non-built-in) commands should all be "protected".
- Also, I made no effort to do the same for fish or zsh. Since this adds no real new feature, I hope this is okay.
- But I did notice that all zsh files have:
https://github.com/junegunn/fzf/blob/488a236b7a4d01e910e0ac80b4794a7a0 …
> use `command` to “protect” further commands

- shell/completion.bash
- shell/completion.zsh
Hey @junegunn.
This would fix #3450 and incorporates a number of improvements and ideas:
- IMO, `__fzf_list_hosts()` should be considered to be a function for user customisation, for which we provide however some reasonable default.
This includes, that it’s up to that function to sort the host list it produces (if desired so) and the remove duplicates, if any.
- To keep things simple for users, I moved out the `username@` prefix handling from it into `_fzf_complete_ssh()` in c64fe9d4ea89e80405837772e7d8b0c876efbeec.
- fbe4c5408a21c981f774feeaaac81af302c9b7b5, makes `completion.bash` to use bash-completion’s `_known_hosts_real()`, if available, and falls back to the previous code for that, if not.
Some open points:
- For `completion.bash`, shall we remove the old host-list code altogether …
> Improve host completion

- shell/key-bindings.fish
Let's see whether the test suite would pass if the old `--is-interactive` is used.
> [fish] exit as well when called from non-interactive shell

- shell/completion.zsh
- shell/key-bindings.zsh
- fix #2094
- The 'emulate' command's ability to accept 'setopt' flags after the shell name is not available for
Zsh versions below 5, causing an unwanted message when sourcing the file.
- This issue was confirmed by @romkatv.
- Despite the original reporter claiming to have a more recent version of zsh, it's recommended they
verify their version again. @fluency03
> fix: #2094

- src/protector/protector_openbsd.go
- src/protector/protector_openbsd.go: add inet permissions for pledge
- fix #3481
> Fix crash on OpenBSD with --listen

- shell/completion.bash
- shell/completion.zsh
> Handle all hostaliases in /etc/hosts

- src/tui/light.go
Not much else to be said about this… urxvt emits slightly different codes than xterm.
> Fix Home, End on rxvt-unicode

- src/protector/protector_openbsd.go
- src/protector/protector_openbsd.go: add tmppath for pledge permissions
- fix junegunn/fzf#3511
> Allow files creation in /tmp on OpenBSD

- README.md
This PR adds a quick line showing how you can install fzf with [Spack](https://github.com/spack/spack). 
Additionally I standardized the markdown table headers to be consistent with the last table in the README. Happy to revert if they were different by design.
> Add Spack installation instructions to README

- src/server.go
The simple success case had only the status line plus a single CRLF, and pedantic HTTP client implementations (`hyper`) stumbled over this. The RFC [requires two](https://www.rfc-editor.org/rfc/rfc9112#section-2.1) even if there's no body.
Fixes #3541.
> Terminate simple server success response with double CRLF

- shell/key-bindings.zsh
> fix(zsh): transform in CTRL_R

- ADVANCED.md
Since `{fzf:prompt}` is being phased out, let's replace the example with `$FZF_PROMPT`.
- Ref #3582
---
The previous PR was unintentionally closed. This implements the same changes as before.
> docs(ADVANCED.md): replace placeholder with env variable for toggle single key binding

- go.mod
- go.sum
This fixes the build for solaris/illumos and removes the extraneous godirwalk dependency.
> dep: update github.com/charlievieth/fastwalk to v1.0.2

- CHANGELOG.md
- README.md
- man/man1/fzf.1
- src/options.go
- test/test_go.rb
For those who prefer to manage default options in a file. If the file is not found, fzf will exit with an error.
We're not setting a default value for it because:
1. it's hard to find a default value that can be universally agreed upon
2. to avoid fzf having to check for the existence of the file even when it's not used
```sh
export FZF_DEFAULT_OPTS=$(cat ~/.fzfrc)
```
Compared to the above, with `FZF_DEFAULT_OPTS_FILE`,
* You don't have to reload your shell configuration file after editing the file
* An external script can modify the configuration file in the background
```sh
fzf() {
FZF_DEFAULT_OPTS=$(cat ~/.fzfrc) command fzf "$@"
}
```
This gives the same benefits of `FZF_DEFAULT_OPTS_FILE` listed above. But you have to manage the function or script yourself.
> Add $FZF_DEFAULT_OPTS_FILE

- shell/completion.bash
This is a fix for an issue reported at https://github.com/scop/bash-completion/issues/1123. The original problem is that the fzf completion setting does not fully preserve the completion settings of `cd` set by `bash-completion-2.12`. More specifically, `bash-completion` completes also variable names through the `-v` option of `complete` when `shopt -s autocd` is specified, but the `-v` option is lost for bash-completion 2.12 when Fzf's completion setting is present. See the original thread for the details.
The problem is that when the completion setting is loaded by `_fzf_handle_dynamic_completion` using `bash-completion`'s `_completion_loader`, only the function specified by `-F` is used by `fzf`. The completion settings specified by other `complete` options are ignored.
The problem …
> [bash] Update the completion setting after `_completion_loader`

- CHANGELOG.md
- README.md
- bin/fzf-tmux
- man/man1/fzf.1
- shell/completion.bash
- shell/completion.zsh
- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
- src/core.go
- src/options.go
- src/reader.go
Close #3464
Close #3647
Related #2705 
Add options for the built-in directory walker and use them to replace the default 'find' commands in the shell extensions.
| Option               | Description                                       | Default              |
| ---                  | ---                                               | ---                  |
| `--walker=OPTS`      | Walker options (`[file][,dir][,follow][,hidden]`) | `file,follow,hidden` |
| `--walker-root=DIR`  | Root directory from which to start walker         | `.`                  |
| `--walker-skip=DIRS` | Comma-separated list of directory names to skip   | `.git,node_modules`               |
> [!NOTE]
> #### Ways to implement `--walker-skip`
>
> ##### Benchmark
> …
> Add walker options and replace 'find' with the built-in walker

- CHANGELOG.md
- README.md
- install
- main.go
- man/man1/fzf.1
- src/options.go
- uninstall
This simplifies the distribution, and the users are less likely to have problems caused by using incompatible scripts and binaries.
* bash
```sh
eval "$(fzf --bash)"
```
* zsh
```sh
eval "$(fzf --zsh)"
```
* fish
```fish
fzf --fish | source
```
> Embed shell integration scripts in fzf binary (`--bash` / `--zsh` / `--fish`)

- CHANGELOG.md
- README.md
- shell/completion.zsh
- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
- test/test_go.rb
This makes it possible to skip one of the above key bindings or completions by setting a variable to an empty string. For example,
FZF_CTRL_T_COMMAND= FZF_ALT_C_COMMAND= FZF_COMPLETION_TRIGGER= \
eval "$(fzf --zsh)"
would leave only the history search. Makes it more convenient then producing the files and changing them myself to not include what I don't want.
This should be working, but for completeness it should also include at least some explaining comment at the top (since there's no docs about these vars?) and something equivalent for bash/fish.
> Make it possible to disable `Ctrl+T` / `Alt+C` / completions

- shell/key-bindings.fish
This fixes a regression from #3649.
> Fix Ctrl-T and Alt-C in fish no longer using last token as search root

- shell/key-bindings.bash
- shell/key-bindings.zsh
Rationale: this way the resulting cd command that ends up in the shell history can be can be reused to get to the same location regardless of present working directory.
> Use realpath for fzf cd

- .github/ISSUE_TEMPLATE/issue_template.yml
- PR #3687 removed the checkbox that asked the user to verify they have the latest version of
fzf. This was due to the introduction of the new `input` field for the 'Output of "fzf
--version"', which made the checkbox seem redundant.
```txt
```
- However, there were minor bug reports where simply updating to a later `fzf` version resolved the
issue. Therefore, it might be beneficial to reintroduce this checkbox, but set the validation to
`false`.
- We could also consider setting the validation for reading the `man` page to `false`. This would
prevent users from being forced to tick the box to open a report, even if they haven't done what
the box suggests. Currently, the `man` page is approximately 20-30 PDF pages long, so it's
understandable if not everything has been read.
```bash
mandoc …
```
> chore: Add new option in issue checklist and modify requirements

- shell/completion.zsh
- shell/key-bindings.zsh
https://github.com/junegunn/fzf/issues/3731#issuecomment-2060699426
Close #3731
Tested with
```bash
export FZF_DEFAULT_OPTS=""
export FZF_COMPLETION_TRIGGER=',,'
alias cat='bat --color=always --number'
source <path to file>
kill ,,
```
> fix: Move 'emulate' command outside interactive check

- Makefile
I was alerted to a build failure of [the COPR build I maintain](https://copr.fedorainfracloud.org/coprs/cyqsimon/fzf/) yesterday, the nature of which is pretty curious. Here are the relevant lines in the build log:
```
+ make FZF_VERSION=0.51.0 FZF_REVISION=260a65b all install
fatal: not a git repository (or any of the parent directories): .git
GOARCH=arm64 go build -a -ldflags "-s -w -X main.version=0.51.0 -X main.revision=260a65b" -tags "" -trimpath -o target/fzf-(Red_arm8
bash: -c: line 1: syntax error near unexpected token `('
bash: -c: line 1: `GOARCH=arm64 go build -a -ldflags "-s -w -X main.version=0.51.0 -X main.revision=260a65b" -tags "" -trimpath -o target/fzf-(Red_arm8'
make: *** [Makefile:161: target/fzf-(Red_arm8] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.xvfXRu …
```
> Fix unreliable GOOS detection

- man/man1/fzf.1
- src/options.go
- src/terminal.go
- src/tui/tui.go
Sets `FZF_HEADERCLICK_LINE` and `FZF_HEADERCLICK_COLUMN` env vars with coordinates of last click inside and relative to the header and fires header-click event.
`printf "header1\nheader2\nheader3\na\nb\nc" | fzf --header-lines=3 --bind "header-click:transform-prompt(echo \${FZF_HEADERCLICK_LINE}x\${FZF_HEADERCLICK_COLUMN})"`
Could be useful for eg. selecting a sort column. Could set a `FZF_HEADERCLICK_WORD` var as well if that is more useful to people.
[Here is a more complex demo with an interactive keyboard](https://gist.github.com/kuremu/4d1441828ebab9d2da67f1298102fc3f) (invoke like `cat /usr/share/dict/words | python keyboard.py`).
>  feature: header-click event for reporting clicks within header

- man/man1/fzf.1
- shell/completion.bash
- src/options.go
Addition of long options for the existing `-i` and `+i` flags.
The rationale behind long options is their self-descriptive nature. Currently, these flags are outliers as they do not have corresponding long options. Introducing them would improve consistency across command-line flags.
> chore: Update flags to include long-form options for case

- plugin/fzf.vim
Despite its title 'Calling fzf#run with a list as source fail (n)vim is used from git bash' the issue in 
https://github.com/junegunn/fzf/issues/3777
of running `:FZF` in Vim in Git Bash was apparently only fixed for Neovim in Git Bash on Windows 11, but not for Vim from Git Bash.
In view of this, replacing /C by ///C might be considered a universal fix.
This PR just proposes the patch in https://github.com/junegunn/fzf/issues/1983 that still seems open.
In view of the fourth item in the most recent 2.45.0 https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues little seems to have changed regarding path conversion of arguments containing forward slashes
> make :FZF work in Vim from Git Bash

- README-VIM.md
- README.md
- bin/fzf-tmux
- doc/fzf.txt
- main.go
- man/man1/fzf-tmux.1
- man/man1/fzf.1
- plugin/fzf.vim
- src/constants.go
- src/core.go
- src/functions.go
- src/options.go
- src/terminal.go
- src/tmux.go
- src/tmux_unix.go
- src/tmux_windows.go
- src/tui/tui.go
Add native `--tmux` option to replace fzf-tmux script.
```
fzf --tmux center
fzf --tmux 80%
fzf --tmux 100%,50%
fzf --tmux left,40%
fzf --tmux left,40%,90%
fzf --tmux top,40%
fzf --tmux top,90%,40%
```
* Simpler and more robust implementation
* Simpler distribution
* Easier to use
* Handles `become` inside tmux popup better
* Properly propagates environment variables
* Requires tmux 3.3 or later
* Only opens in a popup which cannot be zoomed
> Implement native tmux integration

- plugin/fzf.vim
Addresses https://github.com/junegunn/fzf/issues/3809
> Git Bash Mintty: only use cmd.exe if winpty missing

- shell/key-bindings.zsh
enable multiline mode for `zsh`
> feat: zsh multiline mode

- shell/key-bindings.fish
- fix #3826
In addition to the `cd` command, I deemed `history` to be treated as well.
```fish
function history
builtin history --show-time='%F %T '
end
```
```fish
builtin -n
```
> fix: use builtins for cd and history in fish

- shell/key-bindings.zsh
I have some lines in my history that break the new multiline history widget, when pressing ctrl+r I get
```
zsh: no matches found: cd \M-cÂ\M-+クシ\M-c~ィ\M-c\nイズ
```
and no prompt is shown, the issue is with the expansion of the history array, since when I run `echo "${(vk)history[@]}"`, I get the same error.
zsh is trying to expand the (improperly) encoded line for some reason, which can be fixed by setting the `noglob` option.
I am not sure if any of the other widgets would need this option too, or if the issue only arises from zsh's [metafied](https://www.zsh.org/mla/users/2011/msg00154.html) format for history files.
> [zsh] Prevent glob expansion in history widget

- shell/completion.zsh
Close #3841
`zsh` versions prior to **5.1** deal with assignments differently on builtins like `declare, export, local, readonly and typeset`
```sh
❯ ~/.local/zsh-test/bin/zsh-5.0.2 -fxvc 'local scalar=$(echo one word)'
+zsh:1> echo one word
+zsh:1> local 'scalar=one' word
❯ ~/.local/zsh-test/bin/zsh-5.1 -fxvc 'local scalar=$(echo one word)'
local scalar=$(echo one word)
+zsh:1> echo one word
+zsh:1> local scalar='one word'
```
```sh
❯ ~/.local/zsh-test/bin/zsh-5.0.2 -fxvc 'local -a array=(several words)'
zsh:1: missing end of string
❯ ~/.local/zsh-test/bin/zsh-5.1 -fxvc 'local -a array=(several words)'
local -a array=(several words)
+zsh:1> local -a array=( several words )
```
To ensure compatibility with older `zsh` versions, split assignment and declaration when using multiple values …
> chore(shell): Separate declaration and assignment for zsh legacy versions

- shell/completion.zsh
After 22adb6494f4957d0bcc29a821b738b4e5d5796a5, the Zsh completion using `**` fails.
```sh
$ cat **__fzf_generic_path_completion:23: bad pattern: #
```
The cause of this bug is that a comment is in the command substitution.
> Remove comment in command substitution in completion.zsh

- src/protector/protector_openbsd.go
```
vm:~$ uname -a
OpenBSD vm.lab.local 7.5 GENERIC.MP#139 amd64
vm:~$ fzf --version
0.53.0
```
```
vm:~$ fzf --tmux 70%
fzf[30951]: pledge "dpath", syscall 132
zsh: abort (core dumped)  fzf --tmux 70%
```
after adding 'dpath' pledge above test case begins to work, but the next one still fails:
```
vm:/tmp/fzf (master)$ ls | ./fzf --tmux 70%
fzf[17234]: pledge "wpath", syscall 5
zsh: done                 ls -F |
zsh: abort (core dumped)  ./fzf --tmux 70%
```
Solution - add 'dpath' and 'wpath' pledges, after that both test cases work fine.
> Add wpath and dpath pledges on OpenBSD to make --tmux work

- man/man1/fzf-tmux.1
- man/man1/fzf.1
ASCII hyphens (U+002D HYPHEN-MINUS) in the option names (e.g. `-x` and `--extended`) and the code examples in the man page source should be escaped as `\-` (e.g. `\-x` and `\-\-extended`) to prevent them being converted to Unicode hyphens in some environments.
For example, in openSUSE Tumbleweed, the raw ASCII hyphens in the man-page sources are configured to become the Unicode hyphen (U+2010 HYPHEN).  This makes it impossible to search the option names on the `fzf` man page by e.g. `/--extended`<kbd>RET</kbd>.  A problem also arises in copying and pasting option names and code examples from the man page.  It appears to be a normal ASCII hyphen by appearance (in typical terminal fonts) but is not recognized as the ASCII hyphen when specified in command-line arguments of the `fzf` command. …
> [man] Escape hyphens to prevent conversion to Unicode hyphens

- shell/key-bindings.zsh
When `setopt ksh_arrays` in zsh, `${(@kv)history}` gives only the first entry rather than all.
This is breaking the zsh control-r history widget to show only the latest history entry rather than all (which isn't very useful).
I have `setopt ksh_arrays` set in my zshrc.
I believe this is caused by https://github.com/junegunn/fzf/pull/3882/files#diff-c1d0c74baf2323d5dc27290b500868528b9a80be6a0844e998eefb2f9f6ab968R114
specifically the change from `${(kv)history[@]}` to `${(@kv)history}` does not seem to work when you have `setopt ksh_arrays` (it gives back only the one latest history entry).
This fixes it for me, but a potentially better fix could be to add something like `emulate -LR zsh`  at the start of all widgets
> fix zsh ${(@)history} syntax does not work with ksh_arrays

- shell/key-bindings.zsh
Close #3904
Using Apple's default `grep` version and assigning the `GREP_OPTIONS` environment variable with `--color=always`, unintended ANSI escape sequences causing mischief in the correct retrieval of the history entry.
```sh
export GREP_OPTIONS="--color=always"
export PATH="/usr/bin:$PATH"
grep --version
source <(fzf --zsh)
```
1. Use grep `--color=never`, or
2. use the `=~` operator coupled with `MATCH` to catch the matched string in case of a success.
```sh
man 1 zshmisc | less --pattern BASH_REMATCH
```
> fix(zsh): use the '=~' operator instead of grep

- shell/completion.zsh
- shell/key-bindings.zsh
Fix #3859
To test:
```zsh
FZF_CTRL_T_COMMAND="echo -E 'foo\bar\baz'; echo -E 'hello\world'"
_fzf_compgen_path() {
eval $FZF_CTRL_T_COMMAND
}
source shell/key-bindings.zsh
source shell/completion.zsh
```
> [zsh] Fix backslash escaping

- go.mod
- go.sum
- src/reader.go
This commit changes FZF to enforce that all paths are joined with forward-slashes when running on WSL (Windows Subsystem for Linux) even when the FZF binary was compiled for Windows.
Update: github.com/charlievieth/fastwalk to v1.0.5
Fixes:  https://github.com/junegunn/fzf/issues/3859
> Update charlievieth/fastwalk to use forward-slashes on WSL and MSYS

- shell/key-bindings.fish
> harkabeeparolus: If you use standard vanilla fish shell, without any third-party plugins, by default the builtin cd command is wrapped by a function that provides Directory History. This function maintains the dirprev and dirnext lists, which is what enables fish shells's Directory History (cdh and dirh commands, as well as the Alt-Left and Alt-Right hotkeys) to work as intended. When fzf bypasses this function with builtin cd, the previous directory is never saved to the Directory History, and this information is lost to the user.
>
> Source: https://github.com/junegunn/fzf/pull/3830#issuecomment-2230054172
Unfortuantely, we can't use the safe `cd -- …` syntax as there is a small bug in `zoxide`.
> The underlying problem between zoxide and fzf is caused by zoxide actually being …
> fix(fish): handle dash in fzf key bindings

- go.mod
- go.sum
- src/reader.go
**NOTE:** This PR needs to be updated to not use the slices package.
This commit updates [github.com/charlievieth/fastwalk](https://github.com/charlievieth/fastwalk) to [v1.0.7](https://github.com/charlievieth/fastwalk/releases/tag/v1.0.7) which improves MSYS detection and adds optional sorting of directory entries. It also updates fzf to use the SortFilesFirst sort mode which improves the output by making it a bit more sorted and grouped by directory previously entries were visited in directory order (which is basically random). The performance impact of sorting is minimal compared to the cost of the syscalls needed to read directories.
PRs Included:
* https://github.com/charlievieth/fastwalk/pull/25
* https://github.com/charlievieth/fastwalk/pull/27
* …
> Update fastwalk to v1.0.8 for better MSYS detection and sorting

- shell/completion.bash
- shell/completion.zsh
Description
=======
Add fallback for cygwin version of `ps` command. This should fix the `ps: unknown option -- o` error displayed currently when completing `kill **<tab>`.
Fixes: https://github.com/junegunn/fzf/issues/3924
I tried to test the change in zsh completion and the error is indeed gone however I noticed that it doesn't show any content in fzf. I dig a bit and it seems like all of the completions that use `_fzf_complete` have the same issue on my machine, this includes `export **<tab>`, `unalias **<tab>`, `unset **<tab>`, etc.
A cause I can think of is that `mkfifo` is not working the same in windows and that seems to be the mayor difference I see between the bash and zsh completions.
> fix: Add fallback for cygwin ps

- CHANGELOG.md
- shell/completion.bash
All commands with no custom completion defined by setting the default completion function.
Close #3957
```sh
complete | grep pytest
pytest **<tab>
pytest <tab>
complete | grep pytest
pytest **<tab>
pytest <tab>
pytest-2 **<tab>
```
> [bash] Enable fuzzy path completion for all commands

- shell/completion.bash
With the current code, I get this
command cat: command not found
when using any keybinding that does _fzf_complete. Seen on Ubuntu 24.04.1 (GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu))
Fixes: 561e0b0 ("[bash] Use `command` to “protect” further commands (#3462)")
> Use eval to evaluate $post variable as command.

- go.mod
- go.sum
Update fastwalk to [v1.0.9](https://github.com/charlievieth/fastwalk/releases/tag/v1.0.9).
This fixes an issue on Windows when the argument to `--walker-root` was the root of a disk drive (e.g. `C:\`). Instead of walking the disk root `C:\` it walked the current directory. This occurred because we were transforming the fully qualified path `C:\` to the relative path `C:` which caused the current directory to be walked ([docs](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths)).
Fixes: https://github.com/junegunn/fzf/issues/4027
> Update fastwalk to v1.0.9 to fix handling of disk root paths on Windows

- shell/key-bindings.zsh
One of the `zsh` maintainers confirmed the use of `fc -RI` to resolve #4061.
Tested on 5.9 (latest release) and 5.0.1.
There is a bit of peculiarity, as the `history` array stands out as the only one among the history-related commands and widgets that needs a non-empty command to be entered in order to be updated.
https://zsh.org/mla/users/2024/msg00692.html
---
The changes should be sufficiently explained by the comments and the variable names themselves. Alternatively, the man pages for reading up on the syntax are listed below, and important aspects were extracted for ease of review.
```sh
man 1 zshbuiltins | less --pattern fc
man 1 zshbuiltins | less --pattern zmodload
man 1 zshmodules | less --pattern "THE ZSH/PARAMETER MODULE"
man 1 zshoptions | less --pattern SHARE_HISTORY
```
--- …
> fix(zsh): history loading with shared option

- shell/key-bindings.zsh
- hotfix for #4071
When the selection of <kbd>⌃</kbd><kbd>R</kbd> is aborted with <kbd>Escape</kbd>, the widget assigned to the <kbd>↑</kbd> (up arrow key), which is by default `up-line-or-history`, ignores any input.
I don't have an explanation for why this occurs, and why it only happens in combination with the `-I` flag on the `fc` builtin command.
Moving it inside the command substitution alleviates the issue.
Related widget with `fc -RI` usage:
https://zsh.org/mla/users/2021/msg00186.html
---
1. Start a new session and paste the following:
```bash
test-widget() {
fc -RI
}
zle -N test-widget
bindkey '^p' test-widget
bindkey '^[[A' up-line-or-history
```
2. Press <kbd>⌃</kbd><kbd>P</kbd>.
3. Press <kbd>↑</kbd>; notice that nothing happens.
The issue doesn't occur in an environment …
> fix(zsh): move 'fc -RI' inside command substitution

- Dockerfile
The following warnings were emitted when running `make docker-test`:
```
2 warnings found (use docker --debug to expand):
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 11)
- JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 12)
```
This change fixes both of these 2 trivial warnings.
I added the bash `-i` option just in case some of the tests/tools care about whether the shell is an interactive shell or not.  
Even though the tests passed successfully without that flag, I thought I'd add it just in case. It only added 0.5s to the total test time (64.8s -> 65.3s) so it's probably good to keep. Please let me know if you'd want me to remove it.
> docker: fix dockerfile warnings

- man/man1/fzf.1
- src/options.go
This feature can be useful in scrolling to the selected line in the preview window.
For example, it can be used to use fzf as a quick filtering tool for large files while keeping an eye on the selected line as it shows up in the original file.
Example usage:
```bash
man fzf | tee /tmp/tmp.log | fzf \
--reverse \
--exact \
--query 'position' \
--preview 'bat --force-colorization /tmp/tmp.log --highlight-line $(({n}+1))' \
--preview-window '+{n}/2'
```
> Allow specifying '{n}' as the OFFSET in the preview-window flag

- shell/completion.zsh
- shell/key-bindings.zsh
- Resolve #1992
The idea is to gain acces to the `words` array.
```bash
man 1 zshcompwid | less --pattern="^\s+words"
```
The great thing about this array is that the first element contains the name of
the command. The only downside is that the `words` array is available only in
`user-defined completion widgets`, which are created with `zle -C`, as opposed
to `user-defined widgets` created with `zle -N`.
In a command like `ls; foo=bar kill **[TAB]`, `words[1]` will be `kill`.
To understand how the `words` array is constructed, one must read the `zsh`
source code[^1].
> […] the completion system has already done the hard job (and that's not an
> overstatement, I can tell you) of deciding what makes up a word on the command
> line, taking into account quoting and special characters. The …
> refactor: simplify command extraction in zsh completion

- shell/completion.zsh
- shell/key-bindings.zsh
When `setopt ksh_arrays` in zsh, the syntax `$+commands[perl]` doesn't work properly and gives a syntax warning saying `fzf-history-widget:6: bad output format specification`
I think the everything else still actually works, just the warning is a bit annoying.
I have setopt ksh_arrays set in my zshrc.
> fix zsh $+commands[perl] syntax does not work with setopt ksh_arrays

- shell/key-bindings.zsh
- Resolve #4091
- Reopen #4061
Intentionally added to solve an issue with updating the `history` array, which
only updated after the user ran a non-empty command[^1][^2].
There were a couple of issues:
One issue was that executing `fc -RI` seemed to prevent access to recent history
when canceling the `fzf` window with `esc` or `ctrl-c`. Pressing `up` did not
retrieve the expected history. This was mitigated by placing it inside the
command substitution[^3]. However, this led to the issue described in the
referenced ticket.
In the past[^4], it was even reported that there was an unbearable delay when
using `fc -RI`.
[^1]: [ctrl+r no longer pulling from shared history until a command is run succesfully · Issue #4061 · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/issues/4061)
[^2]: …
> revert(zsh): remove 'fc -RI' call in the history widget

- shell/completion.zsh
- Resolve #4088
If a single backtick is used as a trigger, the `words` array fails to populate
with the command elements.
~~The idea here is to temporarily alter the `LBUFFER` before calling
`__fzf_extract_command` by escaping the backtick.~~
The idea is to move the `CURSOR` before the trigger.
This approach seems a bit hacky, which is why this PR is marked as a draft.
Create a list of invalid triggers, since other characters have also been found
to cause the same issue:
Testing covered only ASCII values 32-126; others were excluded for simplicity.
| Symbol  | Common Name  | ASCII | Occurrences in Public Git Repos |
| ------- | ------------ | ----- | --------------------------------------- |
| `&`     | Ampersand    | 38    | 1                                       |
| `;`     | Semicolon …
> fix(zsh): handle backtick trigger edge case

- man/man1/fzf.1
- src/options.go
- src/reader.go
Hi,
I have been trying to search a file or directory with fzf on Windows on multiple drives.
I managed to do it by piping the output of `Get-ChildItem` cmdlet (slow) and then the output of `fd` (faster but not ideal).
It was not a satisfying solution to me so i started to look at the code of fzf and found a solution to this problem by using a comma separated list in the `--walker-root` argument.
I am not proficient in go so the implementation might not be what you are looking for, don't hesitate to guide me towards a solution that suits you.
Best regards,
Martin
> Allow walking multiple root directories

- install
Enhance install script to handle commented and uncommented lines in shell file with user prompts for modification.
- Track commented and uncommented lines in the file.
- Prompt user to append or skip if the line is commented.
- Ensure new lines are added only when necessary, based on user input.
- To the `fish_user_key_bindings.fish`, the original logic would append the line to the end if no corresponding statement was found. I’ve adopted the same behavior for commented lines.
This is my first contribution to this open-source project, and I’m really excited to get involved.
I saw the discussion in issue #3632 and wanted to try implementing the proposed feature.
One concern I have is whether I should write test cases for this change. The existing Ruby tests seem not to support testing the …
> Enhance install script to handle commented and uncommented lines (#3632)

- .github/workflows/linux.yml
- shell/completion.zsh
- test/test_go.rb
Add a completion test for command sequences with different triggers.
Clean up global scope pollution in Zsh:
- `cmd_word` doesn't need to be global since the `zle __fzf_extract_command` call doesn't actually
create a new scope.
- The completion widget is deleted after its usage; its sole purpose is to provide access to the `words` array.
---
~~Draft reason:~~
- ~~Unable to test semicolon (`;`) and backtick (`` ` ``)~~
- ~~Using them in the `test_go.rb` file always ends in failure.~~
```diff
--- a/test/test_go.rb
+++ b/test/test_go.rb
@@ -3744,5 +3744,5 @@ module CompletionTest
triggers = ['**', '~~', '++', 'ff', '/']
-    triggers.concat(['&', '[']) if instance_of?(TestZsh)
+    triggers.concat([';', '`', '&', '[']) if instance_of?(TestZsh)
triggers.each do |trigger|
```
> chore: completion test command sequence

- src/options.go
- src/terminal.go
- src/tui/tui.go
- test/test_go.rb
This PR enables resizing the preview window by dragging its border with the mouse. This works with all border styles except for `none`. Counter-intuitively, having the border only on the opposite side of the window works too - dragging from it will first decrease the preview size to its minimum.
I tested this with quite a lot of different border configurations, although only on Linux. For this I used:
```
./bin/fzf --bind 'ctrl-space:change-preview-window(right,border-horizontal|right,border-left|right,border-right|down,border-rounded|down,border-vertical|down,border-down|down,border-top|left,border-rounded|left,border-horizontal|left,border-right|left,border-left|up,border-rounded|up,border-vertical|up,border-down|up,border-top)' --preview='cat {}'
```
with and without `--padding 2 …
> Make the preview window resizable by mouse drag

- shell/key-bindings.fish
A couple of more changes to fish key bindings: A fix for a bug that removed the leading dot of the query, and an enhancement that enables the expansion of `~/` (more info in commit messages). There is also a small syntax modification to some commands (the position of `--` that marks the end of switches), for consistency with the rest of the code (no actual change).
> [fish] Leading characters: don't strip `.`, expand `~/`

- shell/key-bindings.fish
I remembered why I didn't use the `-f` switch of `string split` in my first PR: it was added in fish version 3.2.0, so it's not the right option for extracting the major/minor version number.
> [fish] Partly revert change of 0167691

- bin/fzf-preview.sh
Reduce the changes of misjudging the type, e.g., when file is under an `image/`
directory.
> Don't include the file name in type information

- Makefile
Some operating systems do not ship with bash by default, e.g. BSDs, which breaks the build.
This PR switches to old-fashioned `sh` without introducing breaking changes.
> Replace bash to sh in Makefile

- ADVANCED.md
- README.md
- man/man1/fzf.1
- src/options.go
- src/tmux.go
This commit adds the `border-native` resulting in
the following:
```
--tmux[=[center|top|bottom|left|right][,SIZE[%]][,SIZE[%]][,border-native]]
```
By default, when not specified, the `-B` flag is passed to the
`tmux popup-window` command such that no border is drawn around
the tmux popup window.
When the `border-native` option is present the `-B` flag is omitted
and the popup window is drawn using the border style configured in
the tmux config file.
Fixes #4156
> add `border-native` option to `--tmux` flag

- src/terminal.go
Currently, header is padded by hardcode length now.
When `pointer`/`marker` set to empty with, it would be better to align header with the list.
```sh
FZF_DEFAULT_OPTS= ./fzf --info=inline --pointer= --header-lines=3
```
fzf.vim `:Buffers`
> fix: make header align with list

- shell/key-bindings.fish
This was originally proposed in #171 to detect support for `bind -M`, but versions _not_ supporting the feature were long archaic, and the detection practically becomes `if true`:
```shellsession
$ codespace:/> fish --version
fish, version 3.1.0
$ codespace:/> bind -M insert # By default there's no mode-specific bindings
$ codespace:/> if bind -M insert &> /dev/null; echo true; end
true
```
It also has a small cost for users with considerable mode-specific bindings, e.g. with `fish_vi_key_bindings` enabled:
```shellsession
$ time bind -M insert &> /dev/null
________________________________________________________
Executed in    1.34 millis    fish           external 
usr time  541.00 micros  541.00 micros    0.00 micros 
sys time  492.00 micros  492.00 micros    0.00 micros
```
(Note in …
> [fish] remove defunct bind feature detection

- shell/key-bindings.fish
Don't add tab after escaped newline.
> [fish] Fix history formatting when perl is missing

- shell/key-bindings.fish
The previous bug fix made the operation 2x slower. With this change, it becomes almost as fast as before.
I have another change I've been testing locally, which begins to display the results instantly (but it's a bigger change and it depends on this code, so it's better to be in another PR). Currently, because the fzf command is being constructed using eval, it becomes blocking (fish blocks when executing builtins). Consider for example:
```fish
for i in (seq 5); echo $i; sleep 1; end | eval (echo fzf)
```
Versus:
```fish
for i in (seq 5); echo $i; sleep 1; end | fzf
```
> [fish] Optimize history formatting without perl

- shell/key-bindings.fish
The purpose of this PR is twofold:
- Allow users to extend the history widget functionality, so that it can delete selected items and reload the list, with something like:
```fish
set -gx FZF_CTRL_R_OPTS '--multi --bind=\'ctrl-x:execute(eval history delete -- (string escape -- {+2..} | string replace -a "\n\t" "\n"))+reload(eval $FZF_DEFAULT_COMMAND)\''
```
- Make the loading of history items non-blocking.
> [fish] Allow setting multi-select and list reload for history

- src/algo/algo.go
Go 1.24 now has a vet check about this that causes `go test` to fail: https://github.com/golang/go/issues/60529
> Fix a non-constant format string

- CHANGELOG.md
- README.md
- man/man1/fzf.1
- plugin/fzf.vim
- src/core.go
- src/options.go
- src/result.go
'pathname' is a tiebreak for prioritizing matches occurring in the tail element of a file path. `--scheme=path` will automatically set `--tiebreak=pathname,length`.
Close #4191
```sh
$ fzf -fs | head -10
src/LICENSE
src/ansi.go
src/core.go
src/item.go
src/tmux.go
src/cache.go
src/proxy.go
src/merger.go
src/reader.go
src/result.go
```
```sh
$ fzf -fs --scheme=path | head -10
src/server.go
src/util/slab.go
.github/workflows/sponsors.yml
src/LICENSE
src/ansi.go
src/core.go
src/item.go
src/tmux.go
src/cache.go
src/proxy.go
```
> Add 'pathname' tiebreak

- shell/key-bindings.fish
Don't use the command substitution syntax: $(cmd)
Fix #4196
---
I tested this change with versions 3.3.1, 3.1.2, and 3.0.2.
The first two work but the last has issues: The `string` command doesn't have the `collect` subcommand (was added in v3.1b1), and `cd` doesn't have the `--` switch (couldn't find the the version that was added).
Version 3.1.1 had broken `eval`. The remaining versions 3.1.0 and 3.1b1, may or may not work.
So, the oldest tested working version is 3.1.2.
> [fish] Fix compatibility with v3.1.2 - v3.3.1

- shell/key-bindings.fish
Instead of exporting a local `$SHELL` containing the location of fish in `$PATH` when global `$SHELL` is not fish, always set `--with-shell` with the actual binary path of fish that the function is running from.
This change ensures that fzf is executing the shell commands using the same fish binary that the function is running with. Can be useful now that the upcoming version of fish can be self-installable (https://github.com/fish-shell/fish-shell/pull/10367), coexisting with a different system installed version, or when testing different builds of fish in general. Tested to work with fish v3.1.2.
> [fish] Improve fish binary path detection

- CHANGELOG.md
- man/man1/fzf.1
- src/options.go
- src/terminal.go
- src/tui/dummy.go
- src/tui/light.go
- src/tui/tcell.go
- src/tui/tui.go
- test/test_layout.rb
Close #2890
Close #1396
I can't think of many use cases. Maybe for really simple menus?
You can't type in queries in this mode, and the only way to trigger an fzf search is to use `search(...)` or `transform-search(...)` action.
```sh
fzf --header '[src] [test]' --no-input --layout reverse \
--header-border bottom --input-border \
--bind 'click-header:transform-search:echo ${FZF_CLICK_HEADER_WORD:1:-1}'
```
* Any action that changes the query is simply ignored.
* Should we respect the initial query? e.g. `fzf --no-input --query a`
* This may give the wrong impression that the "query" is still respected in this mode
* The same can be done using `start` event. i.e. `fzf --no-input --bind start:search:a`
> Add --no-input to hide the input section

- shell/key-bindings.fish
If the current command line token contained a directory with special characters, the script would fail to detect it.
> [fish] Fix for directories with special characters

- bin/fzf-preview.sh
Fix bin/fzf-preview.sh so that image preview works on [ghostty](https://github.com/ghostty-org/ghostty) terminal.
Despite [ghostty supporting the Kitten graphics protocol](https://ghostty.org/docs/features), the image preview does not work even if `kitten` is installed on the system because the script only checks for the `KITTY_WINDOW_ID` environment variable, which is unset in ghostty terminal sessions.
So, when trying to preview images in ghostty, it merely prints the file type:
```console
coko7@example:~$ ./fzf-preview.sh arch_rainbow.png
arch_rainbow.png: PNG image data, 3840 x 2160, 8-bit/color RGBA, non-interlaced
```
Check if `kitten` is installed on the system using `command -v kitten`.
See: https://sw.kovidgoyal.net/kitty/kittens_intro/
> Fix bin/fzf-preview.sh to make image preview work on ghostty terminal

- src/algo/algo.go
- src/algo/algo_test.go
There is an edge-case in FuzzyMatchV1 during backward scan, related to normalization: if string is initially denormalized (e.g. Unicode symbol), backward scan will proceed further to the next char; however, when the score is computed, the string is normalized first, then scanned based on the pattern. This leads to accessing pattern index increment, which itself leads to out-of-bound index access, resulting in a panic.
To illustrate the process, here's the sequence of operations when search is perfored:
1. during backward scan by "minim" pattern
```
xxxxx Minímal example
^^^^^^^^^^^^
||||||||||||
miniiiiiiiim <- compute score for this substring
```
2. during compute score by "minim" pattern
```
Minímal exam
minimal exam <- normalize chars before computing the score
^^^^^^
||||||
minim <- …
```
> Normalize char before pattern lookup in FuzzyMatchV1

- shell/key-bindings.fish
Minor all-around code improvements and clean-ups. No actual changes to the operation of the script. Tested to work with fish versions 3.1.2, 3.7.1 and 4.0b1-430-g5e38a2a46.
Independently of these changes, even though everything seems to work with the beta version 4.0 of fish, there is (again) one test that inconsistently fails (only with v4):
```
TestFish#test_ctrl_r_multiline [test/test_shell_integration.rb:137]:
Expected "" to include "\"foo".
```
> [fish] Small clean-ups and optimizations

- shell/completion.zsh
With zsh, binding `ctrl-\` in `FZF_DEFAULT_OPTS` breaks fzf completion trigger (but fzf-history-widget `ctrl-r` works). Turns out `__fzf_defaults` unescapes the backslash. This PR intends to fix that.
to reproduce: use config below and trigger fzf completions with `$FZF_COMPLETION_TRIGGER`:
```
export FZF_DEFAULT_OPTS='--bind=ctrl-\\:toggle-track'
```
> [zsh/completion] don't unescape FZF_DEFAULT_OPTS

- src/terminal.go
This fixes the bug where the first item was being truncated as discussed in #4282.
> Fix condition for using item numlines cache

- src/terminal.go
- test/test_layout.rb
```sh
FZF_DEFAULT_OPTS= FZF_DEFAULT_OPTS_FILE= fzf --header-border --pointer= --header-lines 1
```
```go
panic: strings: negative Repeat count
goroutine 58 [running]:
strings.Repeat({0x5c5f0633ad10?, 0x5c5f0633ad10?}, 0x1?)
strings/strings.go:624 +0x585
github.com/junegunn/fzf/src.(*Terminal).printHeaderImpl(0xc000190008, {0x5c5f063a3978, 0xc00032c280?}, 0x4, {0x5c5f0656f960, 0x0, 0x5c5f062cde68?}, {0xc000114010, 0x1, 0x1})
github.com/junegunn/fzf/src/terminal.go:2655 +0x1c6
github.com/junegunn/fzf/src.(*Terminal).printHeader.func1(...)
github.com/junegunn/fzf/src/terminal.go:2610
github.com/junegunn/fzf/src.(*Terminal).withWindow(...)
github.com/junegunn/fzf/src/terminal.go:1269
github.com/junegunn/fzf/src.(*Terminal).printHeader(0xc000190008)
github.com/junegunn/fzf/src/terminal.go:2605 …
```
> Fix panic when use header border without pointer/marker

- src/core.go
- src/proxy.go
`tmux popup` doesn't work and immediately returns instead when spawn inside one (`tmux popup tmux popup echo foo` results in an empty popup). For that reason, `fzf --tmux` doesn't work when executed inside a `tmux popup`, for example:
```shell
FZF_DEFAULT_OPTS=--tmux tmux popup 'find . | fzf'
```
And executing `fzf --tmux` inside `fzf --tmux` (as [`forgit`](https://github.com/wfxr/forgit) does, which was how I ran into this issue) also doesn't work, for example:
```shell
find . -type d | FZF_DEFAULT_OPTS=--tmux fzf --bind="enter:execute(find {} -type f | fzf | xargs less)"
```
A popup can be detected by the absence of the `TMUX_PANE` environment variable, so we can simply disable the `--tmux` mode when it is absent. And it also must be excluded for the exports in `runProxy()` so that the …
> Disable tmux popup when already running inside one

- shell/key-bindings.fish
These changes fix issues with newlines in names, and escaped newlines and other characters in command line (more details in commit messages). For the last fix, the `__fzf_parse_commandline` function is rewritten, which now takes advantage of commands/options present in newer fish versions, while maintaining compatibility with the oldest supported version, which is actually v3.1b. All fish versions were individually tested, and they all seem to work, even v3.1.1 despite the reported issues with eval. Dropping support for versions older than v3.2.0 would simplify the code a little, but I think it's better to keep it for now, because v3.1.2 is on Debian 11.
I also have some observations relating the display of file/dir names by fzf:
- When the `--read0` option is not set, the ␤ symbol is not …
> [fish] Fix for newlines and other characters

- man/man1/fzf.1
- src/terminal.go
- test/test_core.rb
I was trying to create a complex command and needed some variables to restore the state of application, but I saw that I could not find some variables because they were not implemented!
Mainly the "FZF_POINTER" variable! I believe it is important that it is accessible! I exported the others to maintain consistency only.
Other thing: The variable 'FZF_LIST_LABEL' was already being exported, but not documented in the manpage!
Thanks.
> Added some missing variables

- shell/key-bindings.fish
The main change of this PR (first commit) is inspired by fish v4: `<ctrl-r>` operates only on the line at cursor, allowing to insert history entries when creating functions in the command line, writing begin/end blocks or constructing multiline commands with `<alt-enter>`.
A few other small changes are included:
- Make `<ctrl-r>` work when both perl and coreutils are missing.
- Simplify the `commandline` call in `fzf-file-widget`.
- Add fish version and dependencies check.
One feature that is present in the default history pager of fish, but not directly available in `fzf-history-widget`, is the ability to delete a history item (`<shift-delete>`). Of course, users can add their own binding in fzf, but the command is quite complex (in order to first restore the history command in its …
> [fish] History improvements and small changes

- CHANGELOG.md
- man/man1/fzf.1
- src/options.go
- src/result.go
- src/result_test.go
- src/terminal.go
- src/tui/tui.go
```sh
go run main.go --bind load:jump
```
Two differences:
* The alternating lines will not be in bold (was a bug)
* The marker column will not be rendered with alternating background color
```sh
go run main.go --color bg:238,alt-bg:237
go run main.go --color bg:238,alt-bg:237 --highlight-line
```
```sh
go run main.go --color bg:238,alt-bg:237,selected-bg:232 \
--highlight-line --multi --bind 'load:select+up+select+up'
```
---
Close #4354
> Add 'alt-bg' color for striped lines

- shell/completion.bash
Currently, fzf sets the `\e[0n` keybinding upon initialization, which is sadly the only way to call readline functions in Bash. Unfortunately, this method is also used by tools like [zoxide](https://github.com/ajeetdsouza/zoxide), causing the keybinding to be overridden:
https://github.com/ajeetdsouza/zoxide/blob/095b270fea283ed0a9d147c2b154a80030f19a4c/templates/bash.txt#L160
Since the only purpose of this particular keybinding appears to be to hack around this particular limitation of Bash, the way I've handled this issue in zoxide is to set the keybinding _right_ before calling it via `printf '\e[5n'`. This PR does the same for fzf.
Context: I'm the author of zoxide, just trying to ensure our plugins don't clash :)
> bash: set keybinding right before printing special character

- SECURITY.md
This PR adds a SECURITY.md file, battle tested in other projects and orgs, (the construct is CC0 ie public domain, for example from here https://raw.githubusercontent.com/itiquette/git-provider-sync/refs/heads/main/SECURITY.md so just reuse)
A SECURITY.md would help anyone assessing the project for use, give a hint of how it handles critical no public security issues, and give anyone a clear instruction on how to report them non public.
**IE, for someone thinking about using fzf in an organization or privately it would give an extra trust factor.**
This policy basically says "send your findings, and we will see if we handle them, we will notify you".
Besides, being a good FOSS practice, makes the project look more professional and it is heavily supported by GitHub …
> Add initial security policy

- src/reader.go
remove redundant word in comment
> chore: remove redundant word in comment

- install
`./install --all` exit with error code because of `uname -smo` in macOS 10.15.7, 12.7.6 (yes, they're old).
```console
$ ./install --all
uname: illegal option -- o
usage: uname [-amnprsv]
No prebuilt binary for  ...
go executable not found. Installation failed.
```
`man uname` doesn't contain `-o` option in macOS 10.15.7, 12.7.6. I can confirm that `man uname` contain `-o` option in macOS 15.6.
So we can fallback to `uname -sm` after trying `uname -smo`.
> Support old uname in macOS

- src/core.go
- src/options.go
- src/terminal.go
There is a [new function](https://pkg.go.dev/maps@go1.21.1#Copy) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: use maps.Copy and maps.Clone
