- .travis.yml
- Rakefile
- src/Makefile
- src/terminal.go
- test/test_go.rb
- test/test_ruby.rb
> Fix CTRL-Y key binding

- .travis.yml
- test/test_go.rb
PS1 trick doesn't seem to work.
> Fix Travis CI build

- README.md
- bin/fzf-tmux
- plugin/fzf.vim
- test/test_go.rb
... and clean up the documentation
> Add fzf-tmux script

- shell/key-bindings.fish
Fix fish commands to stream data to fzf, and don't wait.
> fix fish streams

- install
- shell/key-bindings.zsh
Fixes #363.
Manual testing suggests that the changes work with bash as well as zsh.
> Remove dependency on zsh/pcre module

- src/Dockerfile.android
- src/Makefile
- src/curses/curses.go
> add android build

- shell/key-bindings.zsh
This allows to have a custom widget like the following, which would
additionally accept the line, but only in case of entries being
selected:
fzf-file-widget-with-accept() {
zle fzf-file-widget
if [[ "$?" == 0 ]] && (( $#BUFFER )); then
zle accept-line
fi
}
zle     -N   fzf-file-widget-with-accept
bindkey '\e^T' fzf-file-widget-with-accept
With this `<C-a>t` will launch fzf, and simulate the pressing of "Enter"
afterwards.
> zsh: pass through exit code from fzf with fzf-file-widget

- bin/fzf-tmux
Fixes #643.
Uses the suggestion from https://github.com/tmux/tmux/issues/521#issuecomment-243000022
> Fix grouped tmux session confusion

- plugin/fzf.vim
> use "type" instead of "cat" on windows

- shell/key-bindings.zsh
> don't cd when cancelling alt+c keybind

- README.md
https://github.com/fish-shell/fish-shell/pull/3922
> Mention that the fish bug has been fixed

- shell/key-bindings.fish
This is an enhancement for fish shell key bindings. Currently the <M-c> keybinding only searches subdirectories of cwd. This allows for specifying the root directory to start search from.
```fish
ipwnponies$ pwd                                                                                                              
/Users/ipwnponies/repos/fzf/src/algo
ipwnponies$ ~/repos/fzf<M-C>
>
11/11
/Users/ipwnponies/repos/fzf/bin
/Users/ipwnponies/repos/fzf/doc
/Users/ipwnponies/repos/fzf/man
/Users/ipwnponies/repos/fzf/man/man1
/Users/ipwnponies/repos/fzf/plugin
/Users/ipwnponies/repos/fzf/shell
/Users/ipwnponies/repos/fzf/src
/Users/ipwnponies/repos/fzf/src/algo
/Users/ipwnponies/repos/fzf/src/tui
/Users/ipwnponies/repos/fzf/src/util
> /Users/ipwnponies/repos/fzf/test
ipwnponies$ ..<M-C>
> …
```
> [fish] Accept starting dir for <M-c> key binding

- README.md
Fish shell 2.6.0 was released in June 3: https://fishshell.com/release_notes.html
> update fish comments, because 2.6.0 was released

- shell/key-bindings.zsh
> Fire zsh precmd functions after cd

- man/man1/fzf.1
By the way, thanks for the great project!
> Fix small typo

- man/man1/fzf.1
- src/terminal.go
- src/terminal_test.go
This implements the feature requested in issue #1028.
> Implement flag for preserving whitespace around field

- shell/completion.bash
> [bash] Do not print error when falling back to default completion

- Makefile
See issue [#1320](https://github.com/junegunn/fzf/issues/1320)
> add missing makefile logic for armv8l

- README.md
Just fixed a few common mistakes.
> Typo & grammar fixes in README

- README.md
https://www.youtube.com/watch?v=qgG5Jhi_Els
I've created this screencast which highlights fzf features. It starts with a basics and next moves on to use cases, other than just searching for files. First part of the video is about general command line usage, and second part is devoted to "fzf + Vim" combo. The video can be thought as a documentation complement.
Rationale: Most people use fzf just to search for files, and miss other invaluable features, like changing directory, sending signal to a process, looking up host name to SSH in, etc. This video would be useful for those who learn by watching and should engage people into using fzf at full power.
> Added demo screencast video to readme

- src/history.go
- src/matcher.go
- src/terminal.go
- src/tokenizer.go
- src/tui/light.go
- src/util/chars.go
- Replaced time.Now().Sub() with time.Since()
- Replaced unnecessary string/byte slice conversions
- Removed obsolete return and value assignment in range loop
> Simplified code in various places

- src/terminal.go
- src/tokenizer_test.go
joinTokens is already returning a string.
> Removed unnecessary string conversions

- src/options.go
- src/terminal.go
- src/terminal_test.go
- test/test_go.rb
If present the contents of the selection will be placed in a temporary file, and the filename will be placed into the string instead.
Addresses comments in #1719
> Add 'f' placeholder option for preview pane

- plugin/fzf.vim
Port https://github.com/junegunn/vim-plug/pull/921.
> [vim] Use iconv only if +iconv is enabled

- LICENSE
- README-VIM.md
- README.md
- doc/fzf.txt
- man/man1/fzf-tmux.1
- man/man1/fzf.1
- src/LICENSE
Update copyright year to 2020 and change to multi-year format.
> Update copyright year

- plugin/fzf.vim
fix: #1856
Both of this and #1857 will fix #1856,
but this one won't create new option "ascii".
> consider ambiwidth for border

- .rubocop.yml
- .travis.yml
- src/update_assets.rb
- test/test_go.rb
Separate these changes from the others in #1900
> Run rubocop --auto-correct --disable-uncorrectable

- .travis.yml
- test/test_go.rb
This was originally part of #1900
> Make flaky tests reliable

- plugin/fzf.vim
This PR tries to fix the issue #2041.
> [vim] Don't set wfw, wfh, bh options when opening popup

- plugin/fzf.vim
Vim 8.1.2371
vim/vim@05ad5ff
Nvim 0.4.0
neovim/neovim@9a1675b
> [nvim] Fix floating window requirements

- README-VIM.md
- doc/fzf.txt
This change will make it easier to navigate `doc/fzf.txt`.
> Add tag links for "doc/fzf.txt"

- main.go
Updates number version to the latest major (0.24 -> 0.25).
> update default number version

- src/merger.go
Remove redundant assignment to make code quality slightly better.
> Remove redundant assignment

- src/terminal.go
- test/test_go.rb
> Fix #2374 Don't exit fzf by SIGINT while executing command

- src/tui/light_windows.go
- Increase go routine buffer size
- Add time wait for nonblock getchr()
- Resolves #2429
> Ensure proper ESC seq handling under Windows preview mode

- README.md
Closes https://github.com/junegunn/fzf/issues/2487
> Mention NetBSD package and how to install it

- .github/ISSUE_TEMPLATE.md
- ADVANCED.md
- CHANGELOG.md
- README.md
- bin/fzf-tmux
- shell/completion.bash
- shell/key-bindings.bash
- uninstall
Improvements to bash syntax, spelling and whitespace
> Minor cleanups

- shell/completion.bash
Adding [Helix editor](https://github.com/helix-editor/helix) to bash autocompletion for "hx **<tab><tab>" to work
> Add Helix editor to bash autocompletion

- .github/workflows/winget.yml
- README.md
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @junegunn. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.
You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).
If you want …
> Add Winget Releaser workflow

- README.md
This makes it render correctly on GitHub.
> docs: Fix intention of README

- README-VIM.md
- doc/fzf.txt
Follow-up to d42e708d3140aab099b30014a9cbebafb8b66692.
Fixes #3095.
> doc: Add different prefix for Homebrew on Apple Silicon

- bin/fzf-tmux
- fix #3397 
Commit messages contain further detail. Please let me know if any rebasing needed 🙂 .
> fix: turn off remain-on-exit only on fzf-tmux pane 

- ADVANCED.md
Make use of the `transform` action and the `$FZF_PROMPT` environment variable to
toggle between ripgrep and fzf with a single hotkey.
> docs(ADVANCED.md): Update switch between rg/fzf example with new feature

- README.md
See title. Previous link to highlight is down, updated the readme
> Updated link for highlight command. Previous was broken.

- go.mod
- go.sum
Update charlievieth/fastwalk to resolve issue https://github.com/junegunn/fzf/issues/3706
> mod: update changes/fastwalk to v1.0.3

- shell/completion.bash
- shell/completion.zsh
- shell/key-bindings.bash
- shell/key-bindings.fish
- shell/key-bindings.zsh
- test/test_go.rb
> Respect $FZF_DEFAULT_OPTS_FILE in key bindings and completion

- src/server.go
use errors.New to replace fmt.Errorf with no parameters will much better
> chore: use errors.New to replace fmt.Errorf with no parameters will much better

- CHANGELOG.md
- man/man1/fzf.1
- src/core.go
- src/options.go
- src/reader.go
- src/reader_test.go
- src/terminal.go
- src/terminal_test.go
- src/terminal_unix.go
- src/terminal_windows.go
- src/util/util_unix.go
- src/util/util_windows.go
- test/test_go.rb
Close #3732
This hasn't been tested on Windows.
> Add --with-shell for shelling out with different command and flags

- main_test.go
When tests are ran the `-trimpath` flag `runtime.GOROOT()` returns an empty string. This causes [`TestOSExitNotAllowed`](https://github.com/charlievieth/fzf/blob/2dc3fc40fc9236b249085a550ce9c722e5dcfc21/main_test.go#L141-L174) to fail because [`build.Context.ImportDir()`](https://pkg.go.dev/go/build#Context.ImportDir) cannot find packages in the standard library (without GOROOT it does not know where to look - see issue https://github.com/junegunn/fzf/issues/3748). This commit fixes that by falling back to `go env GOROOT` if `runtime.GOROOT()` returns an empty string. This works because `go env GOROOT` performs more work to identify the GOROOT than `runtime.GOROOT()`.
This should fix https://github.com/junegunn/fzf/issues/3748.
> test: fix TestOSExitNotAllowed to handle empty GOROOT

- shell/key-bindings.fish
- test/test_go.rb
Closes https://github.com/junegunn/fzf/issues/3851
> Merge fish history before searching

- go.mod
- go.sum
> mod: upgrade fastwalk to 1.0.4

- shell/completion.bash
> [bash] Fix infinite retry loop for completion setting without "-F func"

- src/tokenizer.go
- test/test_core.rb
Fix https://github.com/junegunn/fzf/issues/4265.
> Don't trim last field when delimiter is regex

- man/man1/fzf.1
- src/options.go
- src/proxy.go
- src/terminal.go
- src/tui/light.go
- src/tui/light_unix.go
- src/tui/light_windows.go
- src/tui/ttyname_unix.go
- src/tui/ttyname_windows.go
To fix #4242 without unconditionally adding overhead of ttyname.
> Add --tty-default=/dev/tty and --no-tty-default option

- test/test_layout.rb
https://github.com/junegunn/fzf/pull/4405#issuecomment-2934477065
> Fix the CI failure for PR caused by a spelling mistake

- shell/completion.bash
- shell/completion.zsh
The current implementation of the shell function `__fzf_list_hosts` unnecessarily creates many processes to parse the files to list hostnames. The performance can be improved by simplifying the pipelines and reducing the number of forks. Each pipeline can actually be processed by a single AWK script. The number of forks for a single call of `__fzf_list_hosts` is reduced from 17 to 4 by this PR (I'd say 17 forks could be extremely slow up to several seconds depending on the system).
If the size of the processed data is megabytes or more and the system has many cores, one may expect a performance improvement by chaining the commands (which perform non-trivial tasks) in a pipeline and processing them in parallel. However, the `ssh` config, the `known_hosts` records, and `/etc/hosts` would …
> [bash,zsh] Reduce the number of fork & exec

- shell/completion.bash
- shell/completion.zsh
This is the final PR. These are the fixes mentioned in https://github.com/junegunn/fzf/pull/4407#issuecomment-2938682768. Descriptions can be found in the respective commit messages.
I separated the commits to explain each change, but they can be squashed before merging if you want because each change is tiny.
> [bash,zsh] Add fixes to `__fzf_list_hosts`

- src/tui/ttyname_unix.go
> chore: fix function name

- CHANGELOG.md
- src/options.go
- src/options_test.go
- src/terminal.go
- src/tui/tui.go
- test/lib/common.rb
- test/test_exec.rb
- test/test_layout.rb
Make the gutter thinner to match the width of the default pointer character.
Do you like it or not?
(Test cases need to be updated.)
> Style change: thinner gutter

- src/matcher.go
> merger: fix cache never getting cleared
